### ISSUE TITLE
Idea: export a list of RSS feeds

### ISSUE THREAD

**Issue by iandouglas** [GetStream/Winds#1]
After I try the demo, if I want to host my own version, I'd like a way to export the URLs I've entered on winds.getstream.io to then import into my own hosted version.

**Comment by nparsons08** [comment]
Would a CSV do the trick? I think this would be perfect under the reset password field as an export setting. Any other formats that you feel might be helpful?

**Comment by tschellenbach** [comment]
Didn't google reader use something like OPML?
https://en.wikipedia.org/wiki/OPML
