### ISSUE TITLE
Idea: Support installing on sandstorm

### ISSUE THREAD

**Issue by 0xCMP** [GetStream/Winds#10]
Currently TinyRSS is the only option for users of Sandstorm and I'm dying for a better solution. So much that I started writing my own RSS app as well but I don't have the time.

It'd be great if Winds could be configured to deploy on Sandstorm.

https://sandstorm.io

https://docs.sandstorm.io/en/latest/developing/

**Comment by ashleypt** [comment]
I can give this a try, I love installing things manually so automating it into a package should be fun!

Let me know if you have any tips and I'll get started after breakfast :)

**Comment by nparsons08** [comment]
It's all you @ashleypt! Feel free to reach out with any questions :)

**Comment by ashleypt** [comment]
@nparsons08 @0xCMP 

Hey guys, so I've dived in today and so far I've got Winds installed and running just normally on my ubuntu box as a sanity check. I've also followed through on https://docs.sandstorm.io/en/latest/vagrant-spk/installation/ up to the section where I'll need to check out vagrant-spk on git.

Some points

1. Do you guys have any tips for how to integrate this with sandstorm? My current plan is to just go through the main guide, follow the specific instructions for node, and check out any example packages. Then if this is as simple as automating the installation into a specific environment, well, that sounds fun :D
2. Will this require any special integration code on top of basic packaging? If so, I'm up for doing that, but I might need some help to get up to speed with the codebase and figure out how to do that.
3. Is there an irc channel, gitter, or slack for the project or for sandstorm where I can ask for help with quick issues?

**Comment by nparsons08** [comment]
Hey @0xCMP, thanks for diving into Winds. We appreciate the added support. I'd follow the directions on getting started, as they are pretty in depth and cover most cases. If you have specific questions, you can join our Slack channel here: https://winds-rss.herokuapp.com/. Feel free to DM me there w/ any questions.

**Comment by nparsons08** [comment]
Quick update. We've moved away from Slack and are implementing a Gitter channel. You can find it here: https://gitter.im/GetStream/Winds. Cheers! @0xCMP
