### ISSUE TITLE
Can't create an account

### ISSUE THREAD

**Issue by cesdperez** [GetStream/Winds#103]
I'm trying to sign in using my email, but every time it says `INVALID EMAIL OR PASSWORD`. If I try to sign in with Facebook it doesn't work either (this time it redirects to a page saying `The Internet is working (but Winds is not)`).

The email I'm ussing is `cesdperez@gmail.com` and tryied different passwords.

I'm using [winds.getstream.io]().

Browser: Chromium 57.0.2987.110

**Comment by huntercarter** [comment]
I'm experiencing the same issue.

**Comment by artivilla** [comment]
Can you try clearing your storage and trying again: https://cloudup.com/cdncuquxhXT

**Comment by huntercarter** [comment]
No luck. That seems to have corrupted the install, because before I was able to subscribe to topics. Now the page at http://localhost:1337/app/getting-started says "select 3 to continue" but nothing is available to select.

**Comment by owldroid** [comment]
please video instruction to how install winds to localhost

**Comment by dwightgunning** [comment]
Apologies folks, this issue slipped through. We're just getting started on a major update to Winds and we'll definitely look to address these types of challenges and friction with the local install and signup/auth.

I'll assign to @nparsons08 as he's got the lead on Winds.
