### ISSUE TITLE
FIX DEMO LINK

### ISSUE THREAD

**Issue by untotren** [GetStream/Winds#106]
THE DEMO LINK IS NOT A DEMO LINK, JUST A LINK TO THE SERVICE.  MISLEADING, FIX THIS IMMEDIATELY.

**Comment by tschellenbach** [comment]
The demo link points here: https://winds.getstream.io/
Which is just a hosted version of this github repo.

**Comment by untotren** [comment]
I cant see anything of how it functions, it requires an account and it is essentially a marketing page for this software.

**Comment by tschellenbach** [comment]
that's true, you need an account if you want to play around with it. 
(you could install it locally and create an account in your version of the software)

**Comment by untotren** [comment]
Not really a demo then
