### ISSUE TITLE
Docker Container Issue

### ISSUE THREAD

**Issue by Yathushan** [GetStream/Winds#107]
Just pulled the latest image using: 

`docker pull getstreams/winds`

When attempting to start a container with the image for the first time, I get the following error:

`sed: can't read process.json: No such file or directory`

Looking at the Dockerfile, it references to process.json which does not exist in the image.

Can this be changed to either process_dev.json or process_prod.json instead?

**Comment by aipie0066** [comment]
me too

**Comment by nparsons08** [comment]
@Yathushan @aipie0066 Docker support is currently out of the scope of what we can support (at the moment). To fix the issue, please clone the repo and raise a PR with a fix. Thank you!
