### ISSUE TITLE
"Invalid OPML" 

### ISSUE THREAD

**Issue by Yannsb** [GetStream/Winds#110]
Hi !

I tried to import this file (transformed into txt for this post) into Winds from Feedly, however Winds considers it as an "invalid opml". [feedly-5277d6de-0eb5-48d7-9534-4b1809e45613-2017-09-14.opml.txt](https://github.com/GetStream/Winds/files/1302327/feedly-5277d6de-0eb5-48d7-9534-4b1809e45613-2017-09-14.opml.txt)

Can you say why and how to fix it ?

Thank you !

**Comment by dwightgunning** [comment]
Hi, thanks for your note!

I just ran your OPML file through a validator and it looks fine to me. I've attempted to import it into my own Winds account but I don't receive any error.

Can you share to where you saw a message indicating it's "invalid ompl"? I don't see this on page or in the console. It will be helpful to properly replicate what you're seeing.

I'll also assign this issue to Nick, the lead on Winds. He's out-of-office this week but I'm sure he'll take a look as soon as he get's a chance.

**Comment by Yannsb** [comment]
Hi, thanks you for your quick help :)

The message is at this url "https://winds.getstream.io/app/subscriptions#", after clicking on "Import OPML" ![capture](https://user-images.githubusercontent.com/10559729/30430072-48a7c28e-995a-11e7-9d1c-bf2f901d9b12.PNG)

I can't add new links manually either...

In retrospect, I wonder if it's not due to the fact that I didn't select the 3 themes at registration (given that I am already a lot of feeds and that I try above all to highlight the most relevant information in them). Maybe I need to go back and select some, I don't know if it's possible to do it afterward ?

Thank again !

**Comment by Yannsb** [comment]
In creating a new account and following the conventional user path, the problem is resolved...

**Comment by Yannsb** [comment]
I had created my account from the "login with facebook"option. I have recreated a new account with my email address. I notice that i didn't have an account icon, now I have one. I tried to import the OPML, no error button this time but no update of my subscriptions either...

**Comment by dwightgunning** [comment]
>  I tried to import the OPML, no error button this time but no update of my subscriptions either...

I believe this is the same issue I was experiencing with my account.

So I'd say there are potentially three issues here for further investigation:

1. OPML imports not functioning / no error returned.
2. Facebook signup creates account in an invalid state where OPML upload results in an error
3. Manually adding new RSS feeds reports "Feed Missing" error.

**Comment by Yannsb** [comment]
My Winds "facebook signup" account is on my Firefox navigator. It missing User account icon. I can't disconnect even by cleaning the cache and the cookies 🐙 
![capture](https://user-images.githubusercontent.com/10559729/30474118-ded3d04c-9a02-11e7-8b46-7dfa9406bc20.PNG)
My "valid" account is on my chrome navigator. Manual entry works well but not the OPML import who don't add any new subscription. Adding 103 sources manually ? Challenge accepted !

**Comment by dwightgunning** [comment]
Assigning @nparsons08 to take a quick look at this and suggest how we ought to proceed.

**Comment by nparsons08** [comment]
@Yannsb Any chance you can provide me with a bit more information (OS, browser & version, etc.)? I'm unable to fully reproduce, as I'm experiencing the same result as @dwightgunning :(. I am noticing some wonky CSS on your side – are you on IE by chance? Also, are you seeing any error messages in your dev console or network? Thanks!

**Comment by Yannsb** [comment]
Hello, 
excuse me for the response time. 
I'm on Firefox 55.0.3 (64-bit) and Windows 7. 
There is this error in the console "JQMIGRATE: jQuery.browser is deprecated" when i try to import the OPML file but i don't know if it is related.
Do you need more information? 
Thank you for your help

**Comment by nparsons08** [comment]
Hey @Yannsb, thank you for the information. It's definitely possible that it is a front-end issue; however, we're also seeing an unknown issue causing the RSS scraping to fail. After chatting internally, we have decided to close this one out as we're working on a new version of Winds (v2.0). I think you'll be impressed. Stay tuned!
