### ISSUE TITLE
Import OPML from Thunderbird client not working

### ISSUE THREAD

**Issue by alan-garcia** [GetStream/Winds#111]
Hello,
I tried to import this file from Thunderbird email client (renamed to .txt extension for here). Finish importing but nothing happens, it remains the same as before importing it (it's that to say, nothing changed).

[feeds.opml.txt](https://github.com/GetStream/Winds/files/1330790/feeds.opml.txt)

P.D: I'm testing it from the web app (https://winds.getstream.io)

Thank you!

**Comment by dwightgunning** [comment]
Hi @alan-garcia thanks for the report. This is a dup of #110 and we've got some conversation happening over on that issue. Short story is that this will likely remain unfixed as we're currently working hard on Winds 2.0.

Closing. Feel free to comment / discuss further and we can re-open if appropriate.
