### ISSUE TITLE
Bypass auth

### ISSUE THREAD

**Issue by Colir** [GetStream/Winds#112]
Hi. 
i've just install Winds on my localhost.
I'm looking for a way to bypass the auth process (i never receive email, the registration process just not work).

Is it possible ?

than ks you

**Comment by nparsons08** [comment]
Hi @Colir, eliminating auth would require some code modifications on your end. I'd start with the main file. We're actively working on Winds 2.0, so I would suggest holding off on development unless you really enjoy this edition. :)
