### ISSUE TITLE
SESSION_SECRET not documented in README.md

### ISSUE THREAD

**Issue by thundergolfer** [GetStream/Winds#114]
In the `README.md` there's a helpful section explaining the purpose of all the variables in the `.env.example` file. It appears to me that `SESSIONS_SECRET` is not in that section of the README, though it is in `.env.example`. 

Would be good to add it in as it is less confusing for people new to the project. 

Cheers, 

jono

**Comment by nparsons08** [comment]
Hey there @thundergolfer, any chance you can submit a PR with the necessary addition? Thank you!

**Comment by thundergolfer** [comment]
@nparsons08 Yep, probably can.
