### ISSUE TITLE
Help for windows installation

### ISSUE THREAD

**Issue by GokuderaElPsyCongroo** [GetStream/Winds#115]
Hello,

Sorry, I'm a total noob to this, but I can't manage to install the app on Windows. The installation tuto seems to be tailored for OSx or Linux, because I can't use the brew command or anything else. Help please ?
I tried the demo, your app looks wonderful.

Thank you,

**Comment by nparsons08** [comment]
Hey @GokuderaElPsyCongroo, we are deprecating this project in favor for a newer version of Winds that is coming out next month. With that said, we will offer Windows support for that release via Electron. As of now, I would suggest poking around the docs and looking up how to build a release for Windows (I currently do not have access to a Windows machine). Thanks!
