### ISSUE TITLE
Don't send temporary passwords in plaintext

### ISSUE THREAD

**Issue by gRegorLove** [GetStream/Winds#12]
A one-time login link that then forces a password change would be a better practice.

**Comment by nparsons08** [comment]
I'd like to hear your thoughts on the current practice vs. the one that you're preaching -- just to get your perspective. 

Thanks!

**Comment by voltagex** [comment]
Sending a password implies storing it in plaintext (even if you're not). 

Also, email is insecure by default, often with no way for the end user to tell if TLS was used anywhere. Best to use a link that expires after use / after a set amount of time.

**Comment by voltagex** [comment]
http://ux.stackexchange.com/questions/72358/should-password-reset-functionality-email-a-temporary-password-or-just-a-reset-l

**Comment by nparsons08** [comment]
Gotcha. Thank you for the explanation. We'll look into the issue and see what we can do for 0.2.0. As for now, I'd like to share that all passwords are bcrypted.

**Comment by mathias** [comment]
Seconded, the initial email should contain a link with a one-time login token that forces a password reset.
