### ISSUE TITLE
You're demo is down..

### ISSUE THREAD

**Issue by jodumont** [GetStream/Winds#122]
Hi;

You're project seems awesome but with a down demo it's looks like an abandoned project
https://winds.getstream.io/

**Comment by nparsons08** [comment]
Hey @jodumont, we're actually under active development of Winds v2.0. I think you'll really enjoy it. Here's a quick read on 2.0 for you: 

https://medium.com/getstream-io/announcing-winds-2-0-an-electron-app-with-support-for-rss-podcasts-d13dbe812477

Keep an eye on the project (we'll also send you an email) for updates. Sorry for the confusion!
