### ISSUE TITLE
Link is broken

### ISSUE THREAD

**Issue by akaJedi** [GetStream/Winds#124]
Hi, just noticed that some link is broken, please check it out.
" This tutorial explains how the personalization API works ([blogpost](https://bit.ly/personalization-winds)). "

link from example point to https://bit.ly/personalization-winds , after that redirect to  https://getstream.io/personalization-machine-learning-news-feeds-social-networks/ and I got **400 error... We ran into some unexpected problems. We got all hands on deck so everything should be fixed in no time...**

**Comment by nparsons08** [comment]
Looking into the issue, @akaJedi. Thank you for reporting.
