### ISSUE TITLE
Requesting source of image used.

### ISSUE THREAD

**Issue by zeroby0** [GetStream/Winds#125]
Hi,

I'm creating this ticket here because I couldn't find the IRC or similar channel of you guys. Apologies if it's the wrong place.

Could you guys please give me the source to the image behind 'Welcome Nick!' in this image used in https://getstream.io/winds/#.

![screen shot 2018-03-20 at 10 23 15 pm](https://user-images.githubusercontent.com/16903044/37669654-6a20aedc-2c8d-11e8-8b5b-64e76b53e843.png)

I searched your repository for it, but couldn't find it. It would be really helpful if you could.

Thanks :)

**Comment by tilton** [comment]
Hey Dwight- We killed that when we changed that section to showcase "featured" publishers. It is now this:

![2018-03-28 at 9 16 am](https://user-images.githubusercontent.com/1737904/38038713-d84ec728-3268-11e8-8d44-f1c5d49574b6.png)

**Comment by dwightgunning** [comment]
@zeroby0 - what was the interest here? Perhaps send me an email - dwight@getstream.io.

I'll close issue this for now.
