### ISSUE TITLE
Getting multiple errors after installation

### ISSUE THREAD

**Issue by goufang** [GetStream/Winds#128]
http://localhost:1337/api/stream/personalized?limit=25&offset=0&version= 500 (Internal Server Error)
(anonymous) @ Sync.js:76
(anonymous) @ index.js:14
Promise.then (async)
(anonymous) @ index.js:89
dispatch @ applyMiddleware.js:37
(anonymous) @ Feeds.js:43
(anonymous) @ index.js:11
Promise.then (async)
(anonymous) @ index.js:89
componentWillMount @ index.js:131
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountChildren @ ReactMultiChild.js:234
_createInitialChildren @ ReactDOMComponent.js:701
mountComponent @ ReactDOMComponent.js:520
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
_updateRenderedComponent @ ReactCompositeComponent.js:762
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
receiveComponent @ ReactCompositeComponent.js:544
receiveComponent @ ReactReconciler.js:122
_updateRenderedComponent @ ReactCompositeComponent.js:751
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
performUpdateIfNecessary @ ReactCompositeComponent.js:558
performUpdateIfNecessary @ ReactReconciler.js:154
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
ReactComponent.setState @ ReactBaseClasses.js:62
(anonymous) @ Router.js:117
(anonymous) @ createTransitionManager.js:235
(anonymous) @ createTransitionManager.js:90
done @ AsyncUtils.js:76
(anonymous) @ AsyncUtils.js:82
getComponentsForRoute @ getComponents.js:8
(anonymous) @ getComponents.js:32
(anonymous) @ AsyncUtils.js:81
mapAsync @ AsyncUtils.js:80
getComponents @ getComponents.js:31
finishEnterHooks @ createTransitionManager.js:84
next @ AsyncUtils.js:49
(anonymous) @ TransitionUtils.js:90
wrappedNext @ TransitionUtils.js:112
(anonymous) @ index.js:130
Promise.then (async)
isReady @ index.js:126
transitionHook @ TransitionUtils.js:45
(anonymous) @ TransitionUtils.js:116
(anonymous) @ TransitionUtils.js:86
next @ AsyncUtils.js:36
loopAsync @ AsyncUtils.js:53
runTransitionHooks @ TransitionUtils.js:85
runEnterHooks @ TransitionUtils.js:109
(anonymous) @ createTransitionManager.js:77
runTransitionHooks @ TransitionUtils.js:76
runChangeHooks @ TransitionUtils.js:133
finishMatch @ createTransitionManager.js:74
(anonymous) @ createTransitionManager.js:52
next @ AsyncUtils.js:43
loopAsync @ AsyncUtils.js:53
matchRoutes @ matchRoutes.js:237
match @ createTransitionManager.js:48
historyListener @ createTransitionManager.js:229
(anonymous) @ sync.js:128
dispatch @ createStore.js:177
(anonymous) @ Sync.js:49
(anonymous) @ index.js:14
Promise.then (async)
(anonymous) @ index.js:89
handleLocationChange @ sync.js:99
(anonymous) @ useQueries.js:75
(anonymous) @ useBasename.js:67
(anonymous) @ createHistory.js:55
updateLocation @ createHistory.js:54
(anonymous) @ createHistory.js:119
(anonymous) @ createHistory.js:90
next @ AsyncUtils.js:51
loopAsync @ AsyncUtils.js:55
confirmTransitionTo @ createHistory.js:80
transitionTo @ createHistory.js:100
replace @ createHistory.js:135
replace @ useBasename.js:77
replace @ useQueries.js:85
(anonymous) @ createTransitionManager.js:233
handleErrorOrRedirect @ createTransitionManager.js:96
finishEnterHooks @ createTransitionManager.js:81
done @ AsyncUtils.js:18
(anonymous) @ TransitionUtils.js:88
wrappedNext @ TransitionUtils.js:112
(anonymous) @ index.js:130
Promise.then (async)
isReady @ index.js:126
transitionHook @ TransitionUtils.js:45
(anonymous) @ TransitionUtils.js:116
(anonymous) @ TransitionUtils.js:86
next @ AsyncUtils.js:36
loopAsync @ AsyncUtils.js:53
runTransitionHooks @ TransitionUtils.js:85
runEnterHooks @ TransitionUtils.js:109
(anonymous) @ createTransitionManager.js:77
runTransitionHooks @ TransitionUtils.js:76
runChangeHooks @ TransitionUtils.js:133
finishMatch @ createTransitionManager.js:74
(anonymous) @ createTransitionManager.js:52
next @ AsyncUtils.js:43
loopAsync @ AsyncUtils.js:53
matchRoutes @ matchRoutes.js:237
match @ createTransitionManager.js:48
historyListener @ createTransitionManager.js:229
(anonymous) @ sync.js:128
dispatch @ createStore.js:177
(anonymous) @ Sync.js:49
(anonymous) @ index.js:14
Promise.then (async)
(anonymous) @ index.js:89
handleLocationChange @ sync.js:99
(anonymous) @ useQueries.js:75
(anonymous) @ useBasename.js:67
(anonymous) @ createHistory.js:55
updateLocation @ createHistory.js:54
(anonymous) @ createHistory.js:119
(anonymous) @ createHistory.js:90
next @ AsyncUtils.js:51
loopAsync @ AsyncUtils.js:55
confirmTransitionTo @ createHistory.js:80
transitionTo @ createHistory.js:100
replace @ createHistory.js:135
replace @ useBasename.js:77
replace @ useQueries.js:85
componentWillMount @ index.js:633
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
_updateRenderedComponent @ ReactCompositeComponent.js:762
_performComponentUpdate @ ReactCompositeComponent.js:721
updateComponent @ ReactCompositeComponent.js:642
performUpdateIfNecessary @ ReactCompositeComponent.js:558
performUpdateIfNecessary @ ReactReconciler.js:154
runBatchedUpdates @ ReactUpdates.js:148
perform @ Transaction.js:141
perform @ Transaction.js:141
perform @ ReactUpdates.js:87
flushBatchedUpdates @ ReactUpdates.js:170
closeAll @ Transaction.js:207
perform @ Transaction.js:154
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
enqueueUpdate @ ReactUpdates.js:198
enqueueUpdate @ ReactUpdateQueue.js:22
enqueueSetState @ ReactUpdateQueue.js:216
ReactComponent.setState @ ReactBaseClasses.js:62
(anonymous) @ Router.js:117
(anonymous) @ createTransitionManager.js:235
(anonymous) @ createTransitionManager.js:90
done @ AsyncUtils.js:76
(anonymous) @ AsyncUtils.js:82
getComponentsForRoute @ getComponents.js:8
(anonymous) @ getComponents.js:32
(anonymous) @ AsyncUtils.js:81
mapAsync @ AsyncUtils.js:80
getComponents @ getComponents.js:31
finishEnterHooks @ createTransitionManager.js:84
next @ AsyncUtils.js:49
(anonymous) @ TransitionUtils.js:90
wrappedNext @ TransitionUtils.js:112
(anonymous) @ index.js:130
Promise.then (async)
isReady @ index.js:126
transitionHook @ TransitionUtils.js:45
(anonymous) @ TransitionUtils.js:116
(anonymous) @ TransitionUtils.js:86
next @ AsyncUtils.js:36
loopAsync @ AsyncUtils.js:53
runTransitionHooks @ TransitionUtils.js:85
runEnterHooks @ TransitionUtils.js:109
(anonymous) @ createTransitionManager.js:77
runTransitionHooks @ TransitionUtils.js:76
runChangeHooks @ TransitionUtils.js:133
finishMatch @ createTransitionManager.js:74
(anonymous) @ createTransitionManager.js:52
next @ AsyncUtils.js:43
loopAsync @ AsyncUtils.js:53
matchRoutes @ matchRoutes.js:237
match @ createTransitionManager.js:48
historyListener @ createTransitionManager.js:229
listen @ createTransitionManager.js:253
Router_componentWillMount @ Router.js:110
(anonymous) @ ReactCompositeComponent.js:345
measureLifeCyclePerf @ ReactCompositeComponent.js:73
performInitialMount @ ReactCompositeComponent.js:344
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
performInitialMount @ ReactCompositeComponent.js:368
mountComponent @ ReactCompositeComponent.js:255
mountComponent @ ReactReconciler.js:43
mountComponentIntoNode @ ReactMount.js:102
perform @ Transaction.js:141
batchedMountComponentIntoNode @ ReactMount.js:124
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
_renderNewRootComponent @ ReactMount.js:317
_renderSubtreeIntoContainer @ ReactMount.js:399
render @ ReactMount.js:420
renderApp @ index.js:139
(anonymous) @ index.js:163
Promise.then (async)
(anonymous) @ index.js:162
(anonymous) @ bundle.js:1891
__webpack_require__ @ common.js:55
webpackJsonpCallback @ common.js:26
(anonymous) @ bundle.js:1
personalization-feed:1 Uncaught (in promise) {type: "FEEDS_LOAD", data: {…}, error: Error: Internal Server Error at eval (webpack:///./assets/js/middleware/Sync.js?:77:45)}

{type: "INTEREST_PROFILE_LOAD", data: undefined, error: SyntaxError: Unexpected token < in JSON at position 0
    at eval (webpack:///./assets/js/middleware…}
Sync.js:76 Fetch failed loading: GET "http://localhost:1337/api/stream/personalized?limit=25&offset=0&version=".

cannot discover a valid rss feed URI
Request URL: http://localhost:1337/api/rss/discover?url=lifehacker.com%2Frss
Request Method: GET
Status Code: 400 Bad Request
Remote Address: [::1]:1337
Referrer Policy: no-referrer-when-downgrade

**Comment by nparsons08** [comment]
Hi there, this is most likely due to an outdated version of Node.js. Can you please try with the specified version in the README.md file? As a side note, we'll be releasing a beta version of v2.0 in the coming days. You can sign up for beta access at https://getstream.io/winds. Cheers!
