### ISSUE TITLE
Infinite scroll makes footer unreachable

### ISSUE THREAD

**Issue by gRegorLove** [GetStream/Winds#13]
I had a heck of a time getting to the Github link! Had to use dev tools to search for the link. :)

**Comment by nparsons08** [comment]
It's actually been on our radar for awhile now. We're thinking about implementing something similar to https://dribbble.com/shots where it will infinite scroll up to N number of pages and then display a "Load More" button. This would provide access to the footer. Are you interested in giving it a shot?

**Comment by gRegorLove** [comment]
Sounds good. Sorry I forgot to search if this report existed already.

**Comment by nparsons08** [comment]
Fixed by https://github.com/GetStream/Winds/commit/4b29ec8c6f251acd701035e89cfb7b5ca9d2f161
