### ISSUE TITLE
Larger Draggable Area

### ISSUE THREAD

**Issue by BrightnBubbly** [GetStream/Winds#130]
Hey Team!

Can you make more of the header draggable? I managed to drag the window part way off the screen and I can't get it back....

Thanks!
(feel free to pass along a feature request and/or bug template if that is preferable)

**Comment by kenhoff** [comment]
Hey, thanks for the feedback! Yup, we'll add some more draggable zones on the app here. I'll close this once we've fixed and deployed.

**Comment by kenhoff** [comment]
Should be all fixed now - feel free to download the new version from the link that pops up in the app, or from https://getstream.io/winds/. 

Thanks!
