### ISSUE TITLE
Feed Reloading

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#132]
The content in the feed is outdated: 

![image](https://user-images.githubusercontent.com/265409/39087682-e1cb3e38-4561-11e8-8e16-de292034e0b0.png)

After refreshing the page its even more outdated... 

![image](https://user-images.githubusercontent.com/265409/39087701-1ec9f7e8-4562-11e8-9c49-d2ba6c0f4739.png)

**Comment by kenhoff** [comment]
Fixed in https://github.com/GetStream/Winds/commit/4feacb03019f53e34f69cf1c40f030729101df78
