### ISSUE TITLE
Winds hosted app shows apache startpage

### ISSUE THREAD

**Issue by dylan-k** [GetStream/Winds#147]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. Read in several places online about the amazing Winds hosted app
2. go to http://winds.getstream.io/
3. "Apache2 Ubuntu Default Page" ?!

**Expected behavior:** [What you expect to happen]

On the homepage and on a Medium post it says things like "You can use Winds online for free"

**Actual behavior:** [What actually happens]

"Apache2 Ubuntu Default Page" 

**Reproduces how often:** [What percentage of the time does it reproduce?]

100%

### Versions

You can get this information from the manu. Winds > About Winds.

This seems relevant to the app version, not the web version.

**Comment by nparsons08** [comment]
@dylan-k We're looking into this issue. For now, please use **https://getstream.io/winds**. Thank you for bringing this to our attention!

**Comment by nparsons08** [comment]
@sirio7g

**Comment by nparsons08** [comment]
Resolved by @sirio7g
