### ISSUE TITLE
Account deactivation

### ISSUE THREAD

**Issue by wongjn** [GetStream/Winds#15]
How does one delete a registered account? It should not be overly difficult to find the option to delete your own account.

**Comment by tschellenbach** [comment]
A pull request would be much appreciated, shouldn't be too hard.

**Comment by akshatgoel** [comment]
@tschellenbach Hi! I am new to the project and this looks like a beginner issue. Is it OK if I take a stab at it?

I am still exploring the UI so I may be wrong here but there doesn't seem to be a page/view for "user profile" management. There seems to be a sidebar with subscriptions/interests and change password & sign out button. I don't think sidebar is a good place for this action (destructive and obscure action). I am thinking of a subview in the sidebar where such actions can go. Thoughts?

**Comment by artivilla** [comment]
An option for this could be to change the 'Change Password' to 'Settings' and then override the column with 'Delete Account'. And maybe even move the 'Change Password' and other account management info there with a 'Back' label.

<img width="424" alt="winds____powered_by_getstream_io" src="https://cloud.githubusercontent.com/assets/2120159/20255278/47242a6a-aa09-11e6-9a48-7e5efe2dbdcf.png">

**Comment by akshatgoel** [comment]
@artivilla I agree. That's what I meant by a subview for profile management.

**Comment by tschellenbach** [comment]
@tilton what do you think is best in terms of design?

@akshatgoel yes, that would be much appreciated. thanks for contributing!

**Comment by akshatgoel** [comment]
There is another functional aspect to this. Do we allow hard or soft-delete. We can just mark the account deactivated and let user preferences persist, lest user wants to enable their account again.

What do you think?

**Comment by tilton** [comment]
@akshatgoel @tschellenbach My recommendation would be to handle this in two steps. 

The first would be to have a link that says "Permanently delete your account?" at the bottom of the settings panel:

![delete](https://cloud.githubusercontent.com/assets/1737904/20357443/40fe2b9e-abe5-11e6-9938-a0a00d64531a.png)

The next step would be to allow some sort of confirm/deny control on the delete process:

![delete confirm](https://cloud.githubusercontent.com/assets/1737904/20357479/66eb2ab4-abe5-11e6-94fa-a55e9c68fad5.png)

If a user clicks "yes", they should just be directed to winds.getstream.io

**Comment by akshatgoel** [comment]
@tilton So no soft-delete then?

Also, for confirmation, I really like Github (and Heroku)'s way of asking to write name of repository, which can be username in our case before deleting delete. Kind of adds better safeguard against accidental "cat runs on keyboard" scenarios?

**Comment by tilton** [comment]
@akshatgoel I definitely considered doing something like that. It's how we handle deleting feeds at Stream. For this use case, I believe a simple yes/no suffices.

**Comment by nparsons08** [comment]
@akshatgoel Is this something that you decided to pickup for a future PR? If not, we'll pick it up internally in a future release. Please let me know so we're not overlapping on dev :) 💯

**Comment by akshatgoel** [comment]
@nparsons08 Apologies for the delay. I have been a bit busy with day job and couldn't give time to this. 
You can go ahead with the fix. I will pick something else once I am free :)

**Comment by artivilla** [comment]
Can I take a stab at this? Just want to clarify is this to delete or deactivate the user? Are we removing the user from the model?

**Comment by dwightgunning** [comment]
Go for it; a PR would be great.

My preference would be to mark the account as inactive. The login, signup, password reset features should behave as if that user account doesn't exist.

**Comment by nparsons08** [comment]
Since there hasn't been any activity around this topic, we're going to close the issue. Please submit a PR if you're interested in adding this functionality. Thank you!

**Comment by artivilla** [comment]
@nparsons08 I did submit a PR #101 but didn't get any feedback, happy to work on it but new to node so I'm sure it's missing quite a few things.

**Comment by nparsons08** [comment]
@artivilla Awesome. I'll take a look at the code and try to get it merged. Your help is much appreciated. Also, we'd love to send you some swag -- can you send your contact info to nick@getstream.io? Thanks!
