### ISSUE TITLE
hackernoon articels show the same image twice

### ISSUE THREAD

**Issue by JelteF** [GetStream/Winds#152]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

For hackernoon articles the same image is shown twice

### Steps to Reproduce

1. Open winds
2. Click a hackernoon article
3. see a duplicate image

**Expected behavior:** Only see the same issue once

**Actual behavior:** A duplicate image is there
![double image](https://user-images.githubusercontent.com/1162278/39583890-67fc31a4-4ef1-11e8-9ab0-aca9da2c1d7b.png)
**Reproduces how often:** All the time
### Versions

2.0.47 (Linux)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nparsons08** [comment]
We've noticed this on other feeds as well. I have a feeling it has to do with Mercury Parser @kenhoff. Not sure what we can do here...

**Comment by nparsons08** [comment]
Resolved by @kenhoff
