### ISSUE TITLE
Refresh doesn't remember what you were listening to or the position

### ISSUE THREAD

**Issue by JelteF** [GetStream/Winds#154]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

When pressing Ctrl+R to refresh the interface the page your on stays the same, but the podcast stops playing and the position you were at is lost.

### Steps to Reproduce

1. Star a podcast
2. Ctrl+R

**Expected behavior:** Podcast resumes from where you were before refreshing

**Actual behavior:** Podcast stops

**Reproduces how often:** 100%

### Versions

2.0.47 (Linux)

**Comment by nparsons08** [comment]
@kenhoff potential fix - localStorage?
