### ISSUE TITLE
User images all look the same

### ISSUE THREAD

**Issue by JelteF** [GetStream/Winds#155]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Almost everyone has the Gravatar G image. It's nicer to use an identicon, so even if no image is known by gravatar at least everyone has something different. https://en.gravatar.com/site/implement/images/#default-image (you can do that by doing the same request with `default=identicon` as a GET parameter)

**Comment by nparsons08** [comment]
Fixed in https://github.com/GetStream/Winds/blob/master/app/src/components/Avatar/index.js
