### ISSUE TITLE
Algolia search grows out of window for long titles

### ISSUE THREAD

**Issue by JelteF** [GetStream/Winds#158]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Steps to Reproduce

1.  Shrink window a bit
2. Type stuff in the search bar

**Expected behavior:** For the results to stay inside the screen

**Actual behavior:** Before:
![before-outside-screen](https://user-images.githubusercontent.com/1162278/39585762-cafefa1c-4ef5-11e8-9bcd-20f2587f4c64.png)
After:
![after-outside-screen](https://user-images.githubusercontent.com/1162278/39585777-cf57e1c8-4ef5-11e8-9d8e-b70db8107eab.png)

**Reproduces how often:** Always

### Aditional Info

Because the searchbar also grows with the results, it pushes the other menu buttons outside of the screen.

**Comment by kenhoff** [comment]
Already fixed.
