### ISSUE TITLE
Blank Page on Refresh

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#162]
Hit CMD+R to refresh. Blank page with this error:

![image](https://user-images.githubusercontent.com/265409/39667973-589a0e7c-507f-11e8-82e1-f20b232452b0.png)

**Comment by tschellenbach** [comment]
On that note we should probably also run sentry client side. Trying to get users to share information about bugs related to state will be hard.

**Comment by kenhoff** [comment]
unable to repro this in production. closing. feel free to re-open if you still find it happening on specific pages.
