### ISSUE TITLE
Please provide binaries for platforms other than macOS

### ISSUE THREAD

**Issue by RedL0tus** [GetStream/Winds#164]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * [x] Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I can only find macOS binary on the website. 

### Steps to Reproduce

1. Go to the website.
2. Click download
3. Got a macOS binary.

**Expected behavior:** Multi-platform binaries.

**Actual behavior:** macOS only.

**Reproduces how often:** Every time.

### Versions

Current version.

### Additional Information

Come on, the build system supports Linux/Windows, so why not build official binaries for them?

**Comment by nparsons08** [comment]
@RedL0tus This is now resolved. We have distributions for macOS, Linux distros, and Windows. You can download them at https://getstream.io/winds.

**Comment by RedL0tus** [comment]
Thanks!

**Comment by RedL0tus** [comment]
By the way,  @nparsons08 could you please provide binary in .AppImage format ( https://github.com/AppImage/AppImageKit/wiki/Bundling-Electron-apps ), it's painful to use snap in distributions other than Ubuntu.

**Comment by tschellenbach** [comment]
I just pushed a new build, that should resolve the issue you're seeing! @nparsons08 can you test this one more time?

**Comment by RJXIII** [comment]
The link for the Linux download isn't working.
