### ISSUE TITLE
Signup password length validation is off

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/Winds#171]
It says 8 chars are required but it gives green light after 5 chars

![image](https://user-images.githubusercontent.com/88735/39674296-e82d1ece-5149-11e8-9a23-a2f13de23c13.png)

![image](https://user-images.githubusercontent.com/88735/39674298-f2b8e24c-5149-11e8-8f41-4b87487bc36e.png)

**Comment by nparsons08** [comment]
This issue has been addressed.
