### ISSUE TITLE
Add "Dismiss" to follow suggestions

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/Winds#178]
eg. I'd like to dismiss this one from the list of suggestions:

![image](https://user-images.githubusercontent.com/88735/39672898-1ef627dc-5133-11e8-888f-f993fe526a8e.png)

**Comment by kenhoff** [comment]
@tbarbugli - how would you like this to look? I'm not really sure where to add a "dismiss" button without screwing up the design

**Comment by nparsons08** [comment]
https://trello.com/c/UdAZDqSB/904-add-dismiss-to-follow-suggestions-on-homepage
