### ISSUE TITLE
Inconsistent UI for RSS feeds

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/Winds#185]
When you click on a RSS feed (after Read or Listen) sometimes you get the list of followers on the left column, sometimes not.

**Case 1 without followers:**

![image](https://user-images.githubusercontent.com/88735/39691013-5fcee5ec-51dc-11e8-8f55-fbc5b582c61d.png)

**Case 2 with followers:**

![image](https://user-images.githubusercontent.com/88735/39691021-65c8c436-51dc-11e8-837b-59e4c6dfa977.png)

**Comment by kenhoff** [comment]
This is actually due to some feeds being "featured" and having a different UI layout - behaving as expected right now.

**Comment by tbarbugli** [comment]
Changed from bug to regular issue (it still looks very weird)
