### ISSUE TITLE
RSS feeds can't be renamed/re-labeled

### ISSUE THREAD

**Issue by tbarbugli** [GetStream/Winds#188]
Some feeds come with pretty terrible names:

eg. xkcd feed shows up as RSS 2.0

![image](https://user-images.githubusercontent.com/88735/39749001-ea293b04-52b1-11e8-8abd-af83866f0887.png)

It would be great if one could rename or pick a name when adding it

**Comment by nparsons08** [comment]
https://trello.com/c/bh4B72CP/903-ability-to-rename-a-feed-eg-some-feeds-are-simply-named-rss
