### ISSUE TITLE
Voting on 2.1 Feature Set!

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#191]
Let us know what you're most looking forward to in the 2.1 release!

**Comment by HenryQW** [comment]
API? Mobile client?

**Comment by tschellenbach** [comment]
Allow users to skip the onboarding flow.

**Comment by blcarson** [comment]
Theme options possible?

**Comment by HuangYuSan** [comment]
A progressive web app! Is it because of server costs that you don't provide one?

**Comment by timothyjlaurent** [comment]
Mobile client

**Comment by tschellenbach** [comment]
Progressive web app is definitely something we could do thanks for the feedback

**Comment by yandd** [comment]
mobile app

**Comment by dusk0** [comment]
opml import

**Comment by huiyifyj** [comment]
Visit it by browser,
If it can be delayed on linux servers.

**Comment by delockdown** [comment]
Adding twitter user accounts to see the feeds of that particular person

**Comment by citizenk** [comment]
Tools for finding duplicate feeds, dead feeds, and general maintenance

**Comment by citizenk** [comment]
Folders/tags for organizing feeds

**Comment by kundancool** [comment]
- Dark Theme
- Keyboard controls (Play/Pause | Mute | Volume +/-)

**Comment by coma-toast** [comment]
An easier way to see if you are Following something or not.

**Comment by ericschmar** [comment]
More intuitive navigation for reading RSS feeds. If you select a specific feed, navigating back to the cumulative feed is not obvious. Also, some website rendering does not work correctly, depending on the styling. Which I'm sure is probably an issue with the site itself, but more support for off-the-wall sites to at least get some things rendering.

**Comment by HenryQW** [comment]
User-specified filters, which automatically apply actions to feeds/sources.

Eg. If a feed title contains some keywords, prioritise it/mark it as read/star it.

**Comment by tschellenbach** [comment]
A web version is now available (it was a really popular request):
https://winds.getstream.io/

The bugs with OPML import have also been fixed!

**Comment by nonlinear** [comment]
I don't understand the secrecy around other podcast players... I don't mind AT ALL for others to know what I listened to, and when.

So, a public profile with my log, I'm def game. Users can opt out per profile or podcast.

**Comment by nonlinear** [comment]
A way to receive show notes via email helps too... sometimes you're on the go, they comment "it will be in the show notes" and you wish for a "send me show notes for this episode" button. bonus points if it shows WHEN on the show I asked for it.

That's not hard to have and it makes a world of difference. Audio = I'm on the go.

**Comment by mauromassucatti** [comment]
Hi, thanks for the app!

I really like the design! **Clean and Beautifull**! Until now, for the features that you provide, the UX is _good_, and some issues already get the attention in previous comments, like folders, dark theme, etc.

For me, the most important feature that makes all difference here is a **_Mac Menu Bar App_**, working _unattached_/_autonomously_ to the Dock App (that only will be open, when I saw a notification about some news that I want to check).

Of course, there is a pool of possibilities when we talk about Mac Menu Bar Apps, such as: Controlling time to check for news; check all sources now, add an RSS feed, don't disturb (for a period of time), check for updates, preferences, etc.

However, if it only notifies me on the first version, I'll be more than satisfied.

3 other things: 
1. Share button (with the options that already enable on mac is enough);
2. Mac Extension to "Share With" (If I'm inside a website that I want to follow, just share with **Winds** and _voilà_! Or maybe a Safari Extension, but it's almost other software).
3. Not for now, nor for a near future, but I think it will be awesome if I can see what other users assign. I'm not talking about a "Social Network Alike Feature", just find a friend, request "follow" or "see what he follows".

**Comment by iskandergaba** [comment]
Mobile Client. I suggest the app to be hybrid (very flexible in development, reusability of the web code, and easy to make it cross platform)

**Comment by lukasschwab** [comment]
`cmd+f` and `ctrl-f` support in articles.

**Comment by inY2K** [comment]
Mobile of course!

**Comment by boxabirds** [comment]
Google Flutter support. The impression I've got from the front-end community in recent months is that Flutter is a lot more productive than React Native, and also is in beta for web support from the same code base.
