### ISSUE TITLE
Bug: is ORM with MongoDB working?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GetStream/Winds#20]
As said yesterday,
this is an outcome of when I was working yesterday on the Docker.

I was trying to setup my `MONGO_URI` environment variable to something like
```
MONGO_URI="mongodb://localhost:27017/winds"
```
but the application complained that something with `orm` could not be started ( I guess the `sails-mongo` package was not able to use it ).

So I went to your sourcecode and I found [this](https://github.com/GetStream/Winds/blob/master/config/models.js#L20) and [this](https://github.com/GetStream/Winds/blob/master/config/connections.js#L81) where you are actually declaring `MONGO_URL`, which is not the same declared in the `README.md` file.

Therefore I suggest to update the readme with a valid example of connection string that actually works. On my side, the Mongo default installation doesn't have any requirement for user or password, you can just connect and use it.

Thanks in advance,
Julian

**Comment by nparsons08** [comment]
@julianxhokaxhiu Thank you for pointing this out. After looking at the code, it appears that https://github.com/GetStream/Winds/blob/master/config/connections.js#L81 is the correct version. Can you test locally and report back? Potentially with a quick PR? Thanks!

**Comment by tschellenbach** [comment]
Replaced MONGO_URL with MONGO_URI in our codebase.
