### ISSUE TITLE
"There was an error when attempting to create your account. Please try again later."

### ISSUE THREAD

**Issue by dylan-k** [GetStream/Winds#204]
After attempting to create an account, an error message appears, "After attempting to create an account" but it is persistent. I'm running the app on Mac os.

**Comment by networkCat** [comment]
I can confirm this issue!

<img width="375" alt="screenshot at may 14 12-39-26" src="https://user-images.githubusercontent.com/4696430/39992665-dca3ae12-5773-11e8-87cb-464013e9459f.png">

**Comment by dylan-k** [comment]
I built from source locally but that didn't make any difference. The issue remains.

**Comment by tschellenbach** [comment]
We'll look into it. We're pushing for a big release in the next 3 days. Will definitely resolve this.

**Comment by nparsons08** [comment]
@dylan-k This should be resolved in the latest release. You may need to open your developer tools and delete all application data. Thank you for reporting this issue!

**Comment by Pitu** [comment]
Download release v2.0.157 from the website (built 2 days ago) and have the same issue on a clean install.
