### ISSUE TITLE
Idea: setup SMTP email server editing config/emails.js

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GetStream/Winds#21]
This is an outcome of the yesterday outcome of when I was working on the Dockerfile.

I was trying to setup my current email server on Winds, when I found that the application is not able to setup any kind of other server, because of the way the source code is being written up.

Actually you can change the configuration [on this file](https://github.com/GetStream/Winds/blob/master/config/emails.js) although, the reality is that you need ( as an [example of the smtp](https://github.com/ghaiklor/sails-service-mailer#smtpmailer) ) is to totally override [the provider obvject](https://github.com/GetStream/Winds/blob/master/api/services/MailerService.js#L6) inside the Mail Service, changing only Backend, Username and Password is not enough.

My proposal is to make the configuration more flexible, in order to pass the full provider object in the config file. Therefore it will be possible to use any other methodology without the need to rewrite the Service.

Thanks in advance,
Julian

**Comment by tschellenbach** [comment]
Jup, good point, thanks for providing all the details in this ticket.
