### ISSUE TITLE
Idea: change PM2 PORT environment from 80 to 3000

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GetStream/Winds#22]
This is an outcome of the yesterday outcome of when I was working on the Dockerfile.

As you may see the Dockerfile, we are currently exposing the 3000 port, because the application is running within his own user. Since this will affect also any other user that would like to self-host this application, probably on Linux or Mac environments would not be possible, unless you change [the port in the configuration file](https://github.com/GetStream/Winds/blob/master/process.json#L9).

What I suggest, since the pm2 process usually is also being run ( or mostly being run ) by non-root users, is to change the port to something over 1024, in this case I've chosen 3000. Whatever port it will be, please align the change in the [EXPOSE rule of the Dockerfile](https://github.com/GetStream/Winds/blob/master/Dockerfile#L46) and [remove this hacky line](https://github.com/GetStream/Winds/blob/master/docker-entrypoint.sh#L19).

Thank you in advance,
Julian

**Comment by nparsons08** [comment]
That's a good point @julianxhokaxhiu. The whole reason that we're going with port 80 is because it is exposed via PM2 and we don't have to put an NGINX LB in front of the application. Thoughts? We don't want to tie users down to a Docker specific environment.

**Comment by julianxhokaxhiu** [comment]
Considering that the port 80 you probably use it into a production environment, most probably you will serve it via reverse proxy. if you not you'll have special setup behind. so special requirements, special needs, special editing.

But in my opinion we have to assume that every developer must be enabled to run the application also into his non-privileged environment.

talking about docker you can map the 3000 port to the 80 when you run it. so no issues on its side as well.

what do you think?

**Comment by nparsons08** [comment]
Hey @julianxhokaxhiu, do you have time to quickly chat on appear.in? Let me know via email please and we can set something up. Chat soon!

**Comment by nparsons08** [comment]
@julianxhokaxhiu The default now runs on port 8080. I hope this works for you! :)
