### ISSUE TITLE
Why all HackerNews?

### ISSUE THREAD

**Issue by skytreader** [GetStream/Winds#24]
I hope this is the place to raise this concern.

I initially subscribed to

1. Programming
2. Gaming
3. AI & Machine Learning

then I noticed that all the items in my feed are from HackerNews.

While I will not be surprised if a lot of HN items turn up, I would expect items from _other_ sources too. Gaming items aren't always found on HN, for instance.

Is this by design?

**Comment by tschellenbach** [comment]
No that's really weird, do you have a user id, email you've used for signing up or perhaps a screenshot of what you're seeing?

**Comment by skytreader** [comment]
I used chadestioco@gmail.com and it looks like this:

![allhn](https://cloud.githubusercontent.com/assets/1474734/20315326/701df4a6-ab98-11e6-94c9-553a49cca51d.png)

**Comment by nparsons08** [comment]
Thanks @skytreader, we're looking into the issue now.

**Comment by nparsons08** [comment]
@skytreader We've adjusted our algorithm and recently pushed a fix. Please confirm on your end. For now, I'm going to close this out, however, feel free to re-open if the issue persists. Thank you!

**Comment by skytreader** [comment]
The sorting could still do some work but yes! The diversity in my feed is now pretty much falls into my expectations. Thanks!
