### ISSUE TITLE
Unhelpful error message during registration

### ISSUE THREAD

**Issue by Nekuromento** [GetStream/Winds#262]
Registration form doesn't communicate that not all characters are allowed for account user-name (e.g. '.' and '-' characters cause this)
Instead when a generic error message is displayed

[screenshot](https://i.imgur.com/amq4dkp.png)

**Comment by NikkiZabel** [comment]
I am having the same problem, except that I haven't figured out what it is I am doing wrong. I have tried various user names and passwords. Are you aware of any other restrictions it is not specifying?

**Comment by tbarbugli** [comment]
@NikkiZabel can you add the network request you get with the error? You can get that by opening Dev Tools tab (View -> Toggle Developer Tools, Network tab + CTRL-R)

**Comment by NikkiZabel** [comment]
![screenshot from 2018-05-22 12-52-00](https://user-images.githubusercontent.com/33725042/40360906-82b3f996-5dbf-11e8-8d61-1c2ebe3d6952.png)

Not entirely sure what it is you need, but here's a screenshot of that ^

**Comment by TechMoritz** [comment]
Same problem here. I don't know what I'm doing wrong. 

In the console I get the following error message:
> POST http://localhost:8080/auth/signup net::ERR_CONNECTION_REFUSED

**Comment by TechMoritz** [comment]
@tschellenbach Thank you. Version 2.0.208 works well :)

**Comment by nparsons08** [comment]
Thank you @TechMoritz!
