### ISSUE TITLE
Adding regular RSS feed as an Podcast RSS feed results in blog entries interpreted as unplayable podcast episodes

### ISSUE THREAD

**Issue by Nekuromento** [GetStream/Winds#265]
If you provide a regular RSS feed URL when adding a Podcast RSS feed Winds interprets blog entries as unplayable podcast episodes

**Comment by nparsons08** [comment]
https://trello.com/c/6b3Zikva/902-if-you-provide-a-regular-rss-feed-url-when-adding-a-podcast-rss-feed-winds-interprets-blog-entries-as-unplayable-podcast-episode
