### ISSUE TITLE
OPML import fails "Request failed with status code 500"

### ISSUE THREAD

**Issue by sasnfbi1234** [GetStream/Winds#279]
Prerequisites

    Put an X between the brackets on this line if you have done all of the following:
        Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

Description

I've got an .opml export from RSS OWL to test with. I've tried to import this OPML files as new RSS feeds, but when I try to import it i get a "Request failed with status code 500
Steps to Reproduce

1.     Get an .opml export from RSS OWL
2.     Click "New" button in Winds and go to "New RSS".
3.     Click on Import OPML.
4.     Click "Select File" and navigate to the .opml file 
5.     Try to press "Go"... it doesn't show the .opml file as selected/chosen
6.     Wait till error gets displayed

Expected behavior: The .opml file is readily selectable in the file browser and imports

Actual behavior:  Displays error on trying to import 

Reproduces how often: 100%
Versions

Version 2.0.195 (2.0.195)
Additional Information

Running on windows 10

**Comment by sasnfbi1234** [comment]
@nparsons08  sent! thx

**Comment by nparsons08** [comment]
Hey @sasnfbi1234, I'm not sure what's going on but the OPML file you provided seems to be malformed. I'm going to continue testing it out but close this issue out for now. Will be in touch via email.

**Comment by TsukiZombina** [comment]
I have the same problem but importing OPML from feedly.
