### ISSUE TITLE
Links open in-app - get locked into that website.

### ISSUE THREAD

**Issue by isakkeyten** [GetStream/Winds#285]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

[Description of the issue]
Clicking on a link opens the link in Winds app instead of browser.
This in turns locks you in that website and there is no back button to go back to the app.

### Steps to Reproduce

1. [First Step]
Click on Stream RSS
2. [Second Step]
Click on a post with a link (ex Building a Node.js Powered API with Express, Mongoose & MongoDB)
3. [Third Step]
Click on //Next, we take advantage of the Express use method to invoke several of our imported middleware libraries (**cors**, **compression**, and our **body-parser**).// any of the three bolded links.
4. [Fourth step]
You are now on NPM website with no way of getting back to the app without closing the app and turning it on again.

**Expected behavior:** [What you expect to happen]
Either open links in external browser or a back button (option for both preferred)

**Actual behavior:** [What actually happens]
Locked in a third party website untill you re start the app.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions
About winds actually doesn't work so I don't know what version this is. It's the latest at the time of writing.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nparsons08** [comment]
@isakkeyten All links or specific links?

**Comment by isakkeyten** [comment]
@nparsons08 Sorry, don't know, didn't test further. I wrote how to exactly reproduce the bug, but given I don't use the app anymore I don't know if the bug happens under other circumstances too.

**Comment by tschellenbach** [comment]
Anything else we can improve? We're making good progress on 2.1

**Comment by tbarbugli** [comment]
reminds me of #183

**Comment by isakkeyten** [comment]
@tbarbugli Yup. Same. Can be closed since it's fixed there.
