### ISSUE TITLE
How to remove an account?

### ISSUE THREAD

**Issue by m4rr** [GetStream/Winds#286]
There is no option to remove an account inside the app's Settings.

<img width="444" src="https://user-images.githubusercontent.com/868077/40421983-6dbd5b86-5e96-11e8-95a0-1a7290f9a2db.png">

**Comment by nparsons08** [comment]
We're currently working on this feature and will have it deployed soon. Will keep you posted. Thanks for understanding!

**Comment by m4rr** [comment]
Done (version 2.0.284, Mac App Store.) Great!

<img width="227" src="https://user-images.githubusercontent.com/868077/40913954-0710b5c8-67ff-11e8-8eba-a7b65a619917.png">
