### ISSUE TITLE
Add Flatpak or Appimage

### ISSUE THREAD

**Issue by jalberto** [GetStream/Winds#289]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description
In linux Snap is used for packaging, Snap is terrible unstable outside of Ubuntu. Will great to have Wind packaged as Flatpak or Appimage for linux distros.

**Comment by manu-chroma** [comment]
Snap is amazingly terrible. I installed ``Wind`` on fedora 28 using snap and it's not even showing up in gnome menu. Apart from that, snap is very unstable as mentioned above and created lot of system crash reports when the installation was going on. 

Do I need to restart or should it show up by default?

**Comment by nparsons08** [comment]
@manu-chroma you can now download an AppImage from https://s3.amazonaws.com/winds-2.0-releases/latest.html. Hope that helps! :)

**Comment by nparsons08** [comment]
Odd. What are you running? I'll spin up a VM and give it a shot.

**Comment by manu-chroma** [comment]
```
OS: Fedora 28 TwentyEight
Kernel: x86_64 Linux 4.16.8-300.fc28.x86_64
```

**Comment by nparsons08** [comment]
A fix is on the way up to the cloud right now. I'd suggest pulling the latest codebase and re-opening if you have any issues. Cheers! 🥂

**Comment by manu-chroma** [comment]
thank you @nparsons08 :)
