### ISSUE TITLE
Add Media Key Support

### ISSUE THREAD

**Issue by kylemitchell** [GetStream/Winds#290]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Would be fantastic to be able to play / pause podcasts with media keys

### Steps to Reproduce

1. Open Winds
2. Play a Podcast
3. Keyboard play / pause to control audio

**Expected behavior:** Play or pause audio

**Actual behavior:** Nothing (YET)

**Reproduces how often:** 100%

### Versions

Version 2.0.211 (2.0.211)

**Comment by tschellenbach** [comment]
i really like this idea. should be pretty easy as well.

**Comment by nparsons08** [comment]
Would anyone from the community like to make this contribution? We'll send you an awesome Stream t-shirt!

**Comment by leonardovillela** [comment]
Me, i'm working on this issue, I'll soon submit a PR.

**Comment by tschellenbach** [comment]
Awesome :)

**Comment by nparsons08** [comment]
@leonardovillela Hey! How's the PR coming along? Feel free to reach out if you have any questions about the codebase.

**Comment by nparsons08** [comment]
This feature has been added to v2.1! 🎉
