### ISSUE TITLE
Add Option to Skip Onboarding

### ISSUE THREAD

**Issue by Kr4ken-9** [GetStream/Winds#298]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Winds' description: "A Beautiful Open Source RSS & Podcast App"

Winds' reality: An app for stream

Since there is no option to skip onboarding, everyone must register for the stream service even if they don't intend to use it. There should be an option to skip onboarding, if Winds is actually an RSS & Podcast app.

Previously mentioned [here](https://github.com/GetStream/Winds/issues/191)

**Comment by tschellenbach** [comment]
You don't need to signup for Stream if you just use Winds. https://getstream.io/winds/

If you want to install locally you need to configure all of dependencies and services. It's not possible to run Winds without Stream, the majority of the functionality relies upon it. Algolia and Mercury are also required. All of this is documented in the readme. We like using services this is not changing. 

There are other RSS projects that have a different tech stack. This one written in Go for instance is kinda cool: https://github.com/miniflux/miniflux
