### ISSUE TITLE
v2.0.238 not working, assets not found

### ISSUE THREAD

**Issue by alonprince** [GetStream/Winds#299]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

v2.0.238 not working
Failed to load resource: net::ERR_FILE_NOT_FOUND             /static/css/main.395a5eba.css 
Failed to load resource: net::ERR_FILE_NOT_FOUND            main.17a0307d.js 

### Versions

2.0.238 (2.0.238)

**Comment by tschellenbach** [comment]
Platform?

**Comment by alonprince** [comment]
@tschellenbach sorry, I forget to write platform info.
mac os 10.13.4

**Comment by alonprince** [comment]
thx☺️

**Comment by alonprince** [comment]
I get the same error when I download v2.0.240.
I try to download source code and run local build.
Because of I don't have valid identity, build failed.

**Comment by tschellenbach** [comment]
The static files seem to be present in the build. Note that the version on the App Store is still working as well as the web version. https://winds.getstream.io/

@nparsons08 is going to look into it.

**Comment by billy34** [comment]
Same thing on windows 7 with v2.0.240

**Comment by nparsons08** [comment]
A fix is on the way up to the cloud right now. Please reopen the issue if you see any issues regarding this matter. Cheers! 🍻

**Comment by tschellenbach** [comment]
Fixed in 2.0.244 will be available in 10 min or so. this was kinda tricky to figure out. Was related to the package.json "homepage" variable

**Comment by lukasschwab** [comment]
Having this issue, or some variant of it.

+ Winds 2.1.42, downloaded from https://s3.amazonaws.com/winds-2.0-releases/latest.html
+ macOS 10.13.5

Error message in the developer console:

```
GET file:///Applications/Winds.app/Contents/Resources/app.asar/build/index.html net::ERR_FILE_NOT_FOUND
```

**Comment by tschellenbach** [comment]
Fixed in 2.1.44 we tried to eject from create react app and something didn't quite work well with electron builder it seems.

**Comment by lukasschwab** [comment]
Gotcha! It's just that the downloads page is outdated, then.

**Comment by tschellenbach** [comment]
I think you posted this at roughly the same time we pushed the fix :)
https://s3.amazonaws.com/winds-2.0-releases/latest.html
