### ISSUE TITLE
relies on proprietary APIs

### ISSUE THREAD

**Issue by omouse** [GetStream/Winds#3]
some users aren't using stream and others aren't using sendgrid for sending emails, it would be nice if replacements for those were possible.

**Comment by tschellenbach** [comment]
The email backend is pluggable and Sentry can be disabled.
Feel free to fork the repo and replace Stream. This is not something we're considering for the main branch though as we work on Stream and are quite fond of our own technology :)

**Comment by omouse** [comment]
lol ok cool, I just thought I'd bring it up, I'm working on stuff that relies on proprietary APIs as well. It's nice that the email backend is pluggable 👍 Thanks!
