### ISSUE TITLE
Favicon is not displayed

### ISSUE THREAD

**Issue by NansD** [GetStream/Winds#300]
# Favicon is not displayed
When going on the website, there is no favicon displayed. This is also an issue when saving the bookmark.
![image](https://user-images.githubusercontent.com/18481465/40534039-f939ed2c-6004-11e8-9268-125582b5a39b.png)
![image](https://user-images.githubusercontent.com/18481465/40534058-0bb7fdea-6005-11e8-8277-7c3941a93175.png)

**Comment by nparsons08** [comment]
Thanks for the heads up! We'll get one in there shortly. Cheers!

**Comment by NansD** [comment]
Thank you for taking care of it, it will greatly enhance my experience 😄 
I'm happy if my "contribution" was useful 👍

**Comment by tschellenbach** [comment]
its a beauty 
![image](https://user-images.githubusercontent.com/265409/41620178-28af8772-73c6-11e8-99d0-ddd066ba715f.png)
