### ISSUE TITLE
Cannot reset password

### ISSUE THREAD

**Issue by lilithfr** [GetStream/Winds#301]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

On the winds website, the reset password doesn't work. I received the email with the passphrase but after I enter it and click on "Reset Password" nothing happened.
On the winds application, the reset password also doesn't work. I don't receive any email with the passphrase.

### Steps to Reproduce

1. Select reset password on the login screen
2. Enter your email
3. Wait for the email with the passphrase
4. Enter the email, passphrase and new password and click "Reset Password". Nothing happened on Firefox and Chrome.
5. Try to login with the new password, it doesn't work.

**Expected behavior:** The password should be reset.

**Actual behavior:** The password is not reset.

**Reproduces how often:** Always happen.

### Versions

Unknown version, "About Winds" doesn't work but it version downloaded on 24th of May 2018.

### Additional Information

nothing

**Comment by nparsons08** [comment]
Fixed!
