### ISSUE TITLE
Line breaks in code blocks are converted into spaces

### ISSUE THREAD

**Issue by datitisev** [GetStream/Winds#305]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Line breaks in code blocks are ignored, at least for Tuts+ Code.

### Steps to Reproduce

1. Load a Tuts+ Code article
2. Open the original article, and compare code blocks

**Expected behavior:** Line breaks aren't ignored

**Actual behavior:** Line breaks are converted into spaces

**Reproduces how often:** 100%

### Versions

Version 2.0.211

### Additional Information

Using https://code.tutsplus.com/tutorials/a-beginners-guide-to-regular-expressions-in-javascript--cms-31130 as an example.

![artboard](https://user-images.githubusercontent.com/6401250/40578637-719c5a1c-60e5-11e8-9597-71db167dcd37.png)

**Comment by tschellenbach** [comment]
Which RSS feed are you using for this?

Best,
Thierry

**Comment by tschellenbach** [comment]
of course! only tricky part is that the content comes from an API call to an external API. so you have to find a way to add them back in... not sure if its possible. so far we didnt find an alternative for Mercury API yet.

a good easy one is keyboard shortcuts: https://github.com/GetStream/Winds/issues/283 (frontend)

**Comment by nparsons08** [comment]
Hey @edgar971, how's it going with the bugfix? We're here if you need help. Cheers!

**Comment by nparsons08** [comment]
Closing this out as it has become stale. Please reopen if you would like to continue the discussion. Thank you!

**Comment by datitisev** [comment]
Hello. This is very much still an issue.
Different article example:

![image](https://user-images.githubusercontent.com/6401250/41259570-13f902c4-6da2-11e8-86f7-7cb52651af4f.png)
