### ISSUE TITLE
Can't normally parse feed.xml for gitpages(maybe)

### ISSUE THREAD

**Issue by Thunderlbc** [GetStream/Winds#308]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
add new RSS feed with `https://libingchen.me/feed.xml`
2. [Second Step]
after title properly appeared, hit `submit` button
3. [and so on...]
content of feed can't show up, but appears a page says can't parse or no post.

**Expected behavior:** [What you expect to happen]
all post in that website should be inside feeds
**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]
every time = 100%
### Versions
2.0.244 (2.0.244) on Macbook Pro, High Sierra

You can get this information from the menu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Also, is there something wrong with my blogs' feed xml page? 

Thank your guys, 

Best regards,

Li

**Comment by tschellenbach** [comment]
Hi Li,

Thanks for reaching out. I only see 1 post here: https://libingchen.me/feed.xml is that correct?

**Comment by Thunderlbc** [comment]
@tschellenbach  yeah, it's created just for testing~~  there are markdown and gist blocks inside, wondering whether they're supported~

**Comment by nparsons08** [comment]
Hey @Thunderlbc, I just tested the URL and it seems to be parsing correctly. Can you try again? If you run into issues, ping me here and we'll reopen the issue. Thank you!

<img width="1427" alt="screen shot 2018-06-20 at 3 43 21 pm" src="https://user-images.githubusercontent.com/1328388/41686312-d19e69ea-74a0-11e8-91b5-92d3d773124f.png">
