### ISSUE TITLE
Into Links, messy codes appear

### ISSUE THREAD

**Issue by zhanzhixingzhe** [GetStream/Winds#309]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

[Thank you! I'm beginner . I'm a chinese, when i order the rss ,the list is good, but in inside pages there are messy code.]

### Steps to Reproduce

1. [x] add the rss url, for example, http://news.qq.com/newsgj/rss_newswj.xml
2. [x] the list are good  
![the rss was added, good](https://note.youdao.com/yws/public/resource/5a950de94ccd95c34948ab124ead2dab/xmlnote/936F410352D44A48992254C9F76A5A6B/28360)
3. [x] enter one item, chinese characters appear to be mess , English is good
![the pages ,mess ](https://note.youdao.com/yws/public/resource/5a950de94ccd95c34948ab124ead2dab/xmlnote/262F4C61B81046C490DCD280D96FBFE7/28361)
**Expected behavior:** [look better]

**Actual behavior:** [messy codes, about character set ?]

**Reproduces how often:** [mostly]

### Versions

You can get this information from the manu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by yuanchenxi95** [comment]
It is a bug of Mercury API, not the Winds.

The API returns the replacement character(&#xFFFD) in unicode, as it does not support Chinese Characters.
`curl -H "x-api-key: YOUR_MERCURY_TOKEN" "https://mercury.postlight.com/parser?url=http://news.qq.com/a/20180523/004610.htm"`

To add support for other languages, the server might need to a different parser to parse languages other than English, or you can ask Mercury to support different encoding types.

**Comment by zhanzhixingzhe** [comment]
Thank you @yuanchenxi95 
I seem understand

**Comment by nparsons08** [comment]
Closing this out as it's out of our control. Will reopen if the Mercury parser allows for this type of parsing at a later time.
