### ISSUE TITLE
Blank screen after adding new RSS feed on Ubuntu

### ISSUE THREAD

**Issue by benjbrandall** [GetStream/Winds#313]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

After clicking the 'new' button, pasting in an RSS feed, and then selecting the feed from the checkbox, the screen goes blank and I have to quit the app and restart to use it again.

### Steps to Reproduce

1. Click the green 'New' button, 'New RSS'
2. Paste in the feed URL
3. Select the feed with the checkbox displayed
4. Submit

![winds bug](https://user-images.githubusercontent.com/15836153/40641048-097113f4-6321-11e8-8ef9-49c5d003aaf5.png)

![selection_014](https://user-images.githubusercontent.com/15836153/40641110-34e58a7e-6321-11e8-8bf3-0af70096092a.png)

**Expected behavior:** To be redirected to the main screen of the app

**Actual behavior:** Blank screen

**Reproduces how often:** 100%

### Versions

"About Winds" doesn't do anything when clicked. From Ubuntu software center: 2.0.244

### Additional Information

OS: Linux debian 4.15.0-22-generic #24-Ubuntu SMP Wed May 16 12:15:17 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tschellenbach** [comment]
That's not great. I think we have an issue where our backend is returning article.images = null instead of article.images = {}. We'll fix that both on the backend as well as frontend.

**Comment by tschellenbach** [comment]
This issue has been fixed by making a change to the API. So it should work upon refresh now. Thanks for letting us know and feel free to reach out if you run into any other issues!

**Comment by ritiek** [comment]
Thanks @tschellenbach! I can confirm it works now.

However, this might be a separate issue but I am unable to access this particular feed https://openastronomy.org/Universe_OA/rss.xml. For some reason when I add this RSS feed link using https://winds.getstream.io/, it redirects me to https://winds.getstream.io/rss/[object%20Object] that just returns a blank white page.

The feed then also starts showing on the main page
<img src="https://i.imgur.com/LbbGD5E.png" width="300">
but when I open it, it says
<img src="https://i.imgur.com/aKmRKTM.png" width="800">

As you can see the feed obviously has many articles.
