### ISSUE TITLE
Windows: Import OPML not visible

### ISSUE THREAD

**Issue by workingwriter** [GetStream/Winds#316]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Saw that OPML Import was included in current version when someone else had requested this in the v2.1 Features thread. I updated to v2.0.244 on my Windows 7 machine, and followed the instructions given in that thread.

### Steps to Reproduce

1. Clicked **New** button 
2. Looked for OPML option
3. Found only **New Podcast** and **New RSS**
4. Rechecked all menus for OPML setting -- No luck

**Expected behavior:** Somewhere in the interface allowing me to point to an OPML file to add to Winds 

**Actual behavior:** No such thing

**Reproduces how often:** [100%]

### Versions

You can get this information from the manu. Winds > About Winds.

BTW: File > About Winds doesn't display anything! 

### Additional Information

I hope this tells you what you need. Glad to help with any other information.

**Comment by nparsons08** [comment]
Hi @workingwriter, if you click "New" > "RSS" there should be a dropdown for OPML imports. Please doublecheck and reopen this issue if you are still not seeing (preferably with screenshots). Thanks!

**Comment by tschellenbach** [comment]
Also we're going to make this easier to use in the next release. (2.1)

**Comment by workingwriter** [comment]
Good to hear! I did get it working, but I'll note that isoreader exports their Subscriptions file as *.xml (not .opml). While you're in there, you might want to support both extensions.
