### ISSUE TITLE
Use Without Login

### ISSUE THREAD

**Issue by Rictusempra** [GetStream/Winds#324]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Allow users use Winds as a local RSS feeds reader

### Versions

2.0.244

**Comment by tschellenbach** [comment]
Most users want to be able to use on multiple platforms (mobile, web, app). So this is a bit tricky to do.

**Comment by Rictusempra** [comment]
@tschellenbach This is alright. All I request is only `offline mode` despite to have an account.

**Comment by mattcoxonline** [comment]
> Most users want to be able to use on multiple platforms (mobile, web, app). So this is a bit tricky to do. - @tschellenbach

I'm sure you're correct that it's going to be tricky to do; but I do like the idea that you don't have to have an account. It'd be perfectly viable to store subscriptions and read state of posts on the local storage - but you would just have to make it clear that this is not synced cross-device (or cross-browser) until you create an account.

There's a certain audience who would be put off the product if they open it and are greeted with a _Create an Account_ process. It might help "sell" your product if there's an "Unlimited trial mode" where users can try out the product without sync mode / an account.

**Comment by nparsons08** [comment]
Closing this out as it's something that is not within the scope of what is possible with the application.
