### ISSUE TITLE
Recode Decode feed is missing.

### ISSUE THREAD

**Issue by edlau** [GetStream/Winds#326]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Recode Decode podcast feed is missing. This is the link to content https://www.recode.net/podcasts/rss/current

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from the manu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nparsons08** [comment]
You're welcome to add the script manually. Just press the green add button and a form will appear. :)
