### ISSUE TITLE
Performance: Scraping isn't keeping up

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#34]
There are over 2000 feeds to keep in sync now, scraping isn't keeping up. We need to make it a bit more efficient.

Some ideas:

* Prioritize popular feeds while scraping
* Run on multiple cores
* Reduce timeouts
* Disable getMetaInformation for less popular feeds
* Use a task queuing system to distribute the work

**Comment by tschellenbach** [comment]
So I'm thinking about a simple job queue to distribute the scraping workload across multiple servers.  Most self-hosted apps won't need this, so it will be an optional command line argument for the scrape feeds command..

On to the question, which task queueing system is the best?

https://github.com/LewisJEllis/bee-queue
https://github.com/OptimalBits/bull
https://github.com/Automattic/kue

**Comment by Wowl** [comment]
I have another idea: You could try and implement PubSubHubbub to replace polling with subscription, ideally reducing load. Can't give any further details though, since I only just stumbled over it.

**Comment by tschellenbach** [comment]
So far Kue looks like the best option:
https://github.com/Automattic/kue

**Comment by tschellenbach** [comment]
We've prioritized popular feeds and added a task queuing system. We'll need to further improve performance in future releases

**Comment by tschellenbach** [comment]
- We're no longer enriching articles if the hash is the same as an article we've already stored.
- Also fixed an edge case where 400s on the feed url wouldnt trigger the callback on hold up a worker process indefinitely.
