### ISSUE TITLE
Idea: Allow importing a list of RSS feeds in OPML and other formats

### ISSUE THREAD

**Issue by jnareb** [GetStream/Winds#36]
It would be nice to be able to switch from other RSS reader (like e.g. Digg Reader) by importing (uploading) an OPML file or Google Takeout data.

**Comment by nparsons08** [comment]
Hey @jnareb, we now support OPML imports. Just click on the + sign in your header, or click "Upload OPML" in the left sidebar of the subscriptions page. Let us know if you have any issues -- we're here to help!

**Comment by tschellenbach** [comment]
we agree, we've just added this a few days ago. subscriptions -> import opml

![image](https://cloud.githubusercontent.com/assets/265409/20440179/232c8cd0-ad7c-11e6-835a-e4e9838429b6.png)

we're also adding it to the add feed (+) dialog.

**Comment by jnareb** [comment]
@tschellenbach Thanks. I had to reload page to see it.

Waiting to see if Winds would import successfully OPML export from Digg Reader...
