### ISSUE TITLE
Gravatar not always displaying property

### ISSUE THREAD

**Issue by bamadesigner** [GetStream/Winds#361]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

My gravatar displays when I open the settings, but in every other spot it's displaying (what I'm assuming is) the default gravatar image.

### Steps to Reproduce

1. I created an account.
2. Viewed the home page.
3. I can see the default gravatar image at the top of the page.
4. If I click on it, I still see the default gravatar image.
5. If I open settings, I see actual gravatar image.

**Expected behavior:** 
To see my actual gravatar image on all uses.

**Actual behavior:**
Only see my actual gravatar image when I view settings.

**Reproduces how often:** 
I logged out and logged back. Still showing wrong gravatar image.

### Versions

You can get this information from the manu. Winds > About Winds.

I don't see a menu. And the page won't scroll down for me. The .app selector has height set to 100vh.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tschellenbach** [comment]
Fixed in the web version! Will ship in the next app releases as well. Thanks for reporting this

**Comment by bamadesigner** [comment]
Thanks!
