### ISSUE TITLE
The header/menu is inaccessible

### ISSUE THREAD

**Issue by bamadesigner** [GetStream/Winds#363]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

The header/menu is highly inaccessible to users who can't see and who can't use a mouse.

The images need alt attributes and all actions need to be accessible by keyboard, in other words they need to be able to tab to them. Not everyone can use a mouse and click on the items.

### Steps to Reproduce

1. Visit any page.
2. Try to access all header/menu actions using only the keyboard.
3. You can run the site through http://wave.webaim.org/ to view all of the other issues, including missing alt attributes.

**Expected behavior:**
For all images to have a text equivalent, whether via an alt attribute, caption, or nearby.

For all actions to be accessible if you're not using a mouse.

**Actual behavior:**
None of the images have alt text. Only a couple of the actions can be reached by keyboard.

**Reproduces how often:**
Every time.

### Versions

You can get this information from the manu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nparsons08** [comment]
@bamadesigner Are you on the web version of native?

**Comment by bamadesigner** [comment]
@nparsons08 Web version

**Comment by nparsons08** [comment]
@bamadesigner Would you be up for giving this a shot? We're getting pretty swamped with the heavy amount of users flooding in. :) I guess it's a good thing haha.

**Comment by nparsons08** [comment]
Closing this issue as it has become stale. Please re-open if you'd like to contribute to this issue. Thank you!
