### ISSUE TITLE
Does not launch on Wayland / Ubuntu 18.04

### ISSUE THREAD

**Issue by vinay-gujar** [GetStream/Winds#364]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Winds does not launch on the Wayland display manager on Ubuntu 18.04
Although it works perfectly on Xorg 

### Steps to Reproduce

1. Log into Wayland session on Ubuntu 18.04
2. Launch Winds

**Expected behavior:** 
Winds launches normally through app launcher and/or terminal

**Actual behavior:** 
Winds does not launch on Wayland

**Reproduces how often:** 
100%

### Versions
Winds snap [stable] 2.0.293

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by nparsons08** [comment]
@vinay-gujar Are you seeing any error messages that may help us debug this issue? Thank you!

**Comment by vinay-gujar** [comment]
@nparsons08 No, there are no visible error messages.

**Comment by nparsons08** [comment]
@vinay-gujar Thanks for the quick response. I'll spin up an Ubuntu Wayland instance and see if I can reproduce. Stay tuned.

**Comment by vinay-gujar** [comment]
@nparsons08 Thank you, will do!

**Comment by nparsons08** [comment]
Hey @vinay-gujar, I was able to reproduce the issue; however, the application eventually loaded after about 30-60 seconds. Not ideal, but provided the bugs we have so far, we're going to throw this on the backburner for now. I'll try to get some debugging going in my free time. Thanks!

**Comment by jamespotz** [comment]
This happen on my end using Pop OS 19.10
`DISABLE_WAYLAND=1 snap run winds` work.
Is there a snapcraft.yml file we can add the env variable?

**Comment by mahboubii** [comment]
@jamespotz could you try with the latest build? https://s3.amazonaws.com/winds-2.0-releases/releases/Winds-3.2.0.AppImage
