### ISSUE TITLE
Appimage missing on https://getstream.io/winds/

### ISSUE THREAD

**Issue by scottsweb** [GetStream/Winds#365]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

The download for the Appimage is currently broken on https://getstream.io/winds/. It looks like an authentication issue with S3.

**Comment by nparsons08** [comment]
Looking into this now @scottsweb. Thank you for the heads up!

**Comment by nparsons08** [comment]
@scottsweb This issue has been fixed and will be resolved in the next deploy (likely later today). For now, you can use the direct URL: https://s3.amazonaws.com/winds-2.0-releases/releases/Winds-2.0.293-x86_64.AppImage

**Comment by scottsweb** [comment]
That is great, thanks for looking into it so quickly. I am looking forward to testing the app!

**Comment by alexwender1** [comment]
Again, AppImage is unavailable. When downloading from <getstream.io/winds>, the following message / error of the site appears:

![captura de tela_selecionar area_20181228134736](https://user-images.githubusercontent.com/45263160/50520386-30706800-0aa7-11e9-8b25-1d34e60b240d.png)
