### ISSUE TITLE
Where is the AppImage?

### ISSUE THREAD

**Issue by buckle2000** [GetStream/Winds#373]
https://s3.amazonaws.com/winds-2.0-releases/latest.html

The link is broken:

https://s3.amazonaws.com/winds-2.0-releases/releases/Winds-2.0.309-x86_64.AppImage

```
AccessDeniedAccess DeniedAD3DE14783048B44UXblsgSxutMinLzYia4v2DA7sHzbQxQRqBlHp35sTEC7D5hqVYzl1PgeSd1D0t8XRy+w9JI/ajA=
```

**Comment by ahswch** [comment]
i meet the same problem.can't download the releases by 'https://s3.amazonaws.com/winds-2.0-releases/latest.html'

**Comment by tschellenbach** [comment]
I think it's a typo in the filename... @nparsons?

**Comment by tschellenbach** [comment]
Looks like it's fixed. Can you try again?
https://getstream.io/winds/

**Comment by buckle2000** [comment]
It's fixed. :+1:
