### ISSUE TITLE
Youtube Feeds

### ISSUE THREAD

**Issue by mhingston** [GetStream/Winds#377]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Youtube feeds aren't parsed by Winds.

### Steps to Reproduce

1. Click New > New RSS
2. Paste in Youtube feed URL: https://www.youtube.com/feeds/videos.xml?channel_id=UCaKZDEMDdQc8t6GzFj1_TDw
3. Select the feed and click submit
4. Wait a few minutes before clicking the feed in Winds to see the error message (no content).

**Expected behavior:** [What you expect to happen]
Feed is parsed and rendered by Winds

**Actual behavior:** [What actually happens]

    We haven't found any articles for this RSS feed yet :(

    It might be because the RSS feed doesn't have any articles, or because it just got added and we're still parsing them. Come check back in a few minutes?

    If you're pretty sure there's supposed to be some articles here, and they aren't showing up, please file a GitHub Issue.

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%

### Versions

You can get this information from the manu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

Using the webapp - https://winds.getstream.io/

**Comment by tschellenbach** [comment]
yeah we don't have video support just yet. (at least not when the rss feed specifies it as an enclosure)
lets see if we can get this in for 2.1 release

**Comment by tschellenbach** [comment]
WIP is here: https://github.com/GetStream/Winds/pull/385

**Comment by tschellenbach** [comment]
support is added for this in 2.1, now you can follow ninja's youtube channel all day long!
