### ISSUE TITLE
Idea: Rename feeds

### ISSUE THREAD

**Issue by hyperfekt** [GetStream/Winds#39]
For various reasons feeds could have an uninformative name, for example when subscribed to subfeeds of publications, which cover only part of a topic but their name doesn't show that. There are quite a few scenarios.
I propose being able to change the display name of a feed.

**Comment by nparsons08** [comment]
@tschellenbach What are your thoughts on this / how to implement?

**Comment by nparsons08** [comment]
Since there hasn't been any activity around this topic, we're going to close the issue. Please submit a PR if you're interested in adding this functionality. Thank you!
