### ISSUE TITLE
Idea: Secondary links

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#4]
Show a secondary link to the comments for sites like Product Hunt, Reddit, HNews, Lobsters, DesignerNews etc

**Comment by artivilla** [comment]
Are we talking about showing links for feeds that have comments? Is that data being currently pulled or we need to create a separate endpoint. Would love to take a stab at this. :)

**Comment by tschellenbach** [comment]
From the looks of it will take a bit of work for every feed where we want to support this:
https://github.com/GetStream/Winds/commit/5210283d798149d81795a795466d628403599b22

Which RSS feeds do you read?

So the idea is to have a link to the comments section on Hnews, Designernews, Lobsters etc.

**Comment by artivilla** [comment]
Quite a few, not sure how many of these are popular. Not sure if this method is scalable but I can take a stab at adding some.

![screen shot 2016-11-15 at 12 54 53 pm](https://cloud.githubusercontent.com/assets/2120159/20317184/fb2671b0-ab32-11e6-943b-17893b1ce6db.png)

Is there a way to add email subscriptions that don't have RSS to a reader as well. It would make for a great value add on, that would set Winds apart.

**Comment by tschellenbach** [comment]
That's a long list, did you see that we've just added OPML support? So you can batch import those subscriptions to Winds. (it's not entirely perfect yet though)

![image](https://cloud.githubusercontent.com/assets/265409/20330651/8525a3ca-ab5d-11e6-8401-971b82c84f59.png)
