### ISSUE TITLE
Can't add new feed

### ISSUE THREAD

**Issue by MadMikeyB** [GetStream/Winds#406]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I'm trying to add a new feed - https://www.gamefront.com/feed/news and I just get "Oops, something went wrong. Please try again later."

### Steps to Reproduce

1. Click "New" 
2. RSS Feed
3. Enter https://www.gamefront.com/feed/news into "Add New RSS Feed" modal
4. See error.

**Expected behavior:** Add and parse feed from gamefront.com news feed.

**Actual behavior:** "Oops, something went wrong. Please try again later."

![screen shot 2018-06-19 at 18 53 25](https://user-images.githubusercontent.com/831828/41615022-13bebf6e-73f2-11e8-9a6c-e2f720384331.jpg)

**Reproduces how often:** 100%

### Versions

Version 2.1.0 (2.1.0)

### Additional Information

I built the feed in question myself, was curious to see if it worked in a third party application which isn't FireFox's in built reader. FireFox parses it and the feed does validate as you can see here: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.gamefront.com%2Ffeed%2Fnews

**Comment by nparsons08** [comment]
Hey @MadMikeyB, we're looking into the issue and will get back to you as soon as possible! Thanks for reporting this.

**Comment by tschellenbach** [comment]
Tried this out, and it indeed doesn't work. Something related to invalid/different SSL

```
Error: write EPROTO 140736089965440:error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/s23_clnt.c:802
```

**Comment by tschellenbach** [comment]
Looks like we can resolve this issue by using a newer version of node... Going to add that to the backlog. @tbarbugli it looks as though this is solved in 10.4.1

**Comment by MadMikeyB** [comment]
Wow, super fast response. Thanks @nparsons08 and @tschellenbach - amazing!

**Comment by tschellenbach** [comment]
Now running Winds on 10.5.0 which resolves this SSL issue. Gamefront now works: https://winds.getstream.io/rss/5b2aca6a639896d0a87c15d9

Thanks for letting us know! It does seem that we have some OG scraping issues, @Nekuromento is looking into that.

![image](https://user-images.githubusercontent.com/265409/41686298-ca16ef94-74a0-11e8-85e2-d761a3c86255.png)

**Comment by tschellenbach** [comment]
Ah, looks like this is caused by the urls in the feed being broken. This gives a 404: https://www.gamefront.com/forums/playerunknown-s-battlegrounds/pubg-s-new-map-sanhok-is-coming-june-22nd-along-with-some-major-ui-changes

**Comment by MadMikeyB** [comment]
Thanks @tschellenbach - I'll get those fixed :)

**Comment by MadMikeyB** [comment]
hi @tschellenbach are the URL's cached in Winds? I've fixed the issue but the app still shows the old ones :)

**Comment by tschellenbach** [comment]
See the rss.md file for how we handle uniqueneds
