### ISSUE TITLE
Windows defender flagging .exe as virus.

### ISSUE THREAD

**Issue by N-Upchurch** [GetStream/Winds#413]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Upon download from MS Edge, windows defender interrupts download and removes .exe. Exe flags as a trojan.

### Steps to Reproduce

1. Download exe using edge
2. Profit

**Expected behavior:** The exe would run, without being flagged as a virus

**Actual behavior:** The exe does not run, and is flagged as a virus

**Reproduces how often:** 100%

### Versions

Download available from project page

### Additional Information

Download also failing frequently

**Comment by nparsons08** [comment]
Unable to reproduce. Please open if the issue persists.
