### ISSUE TITLE
Fail to add desktop entry on Linux (openSUSE Leap 15)

### ISSUE THREAD

**Issue by jcamilom** [GetStream/Winds#419]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

The desktop entry fails to be added using the AppImage.

### Steps to Reproduce

1. Download the AppImage
2. Make it executable `chmod +x Winds-2.1.0-x86_64.AppImage`
3. Execute the application `./Winds-2.1.0-x86_64.AppImage`
4. Say yes to "Would you like to integrate /home/user/Downloads/Winds-2.1.0-x86_64.AppImage with your system?

**Expected behavior:** To have a desktop entry integrated with my system.

**Actual behavior:** Error message in the console when executing the AppImage and saying "yes" to the app system integration.

Error on file "/tmp/.mount_Winds-VrlHqf/winds.desktop": Key file contains line “For more information, visit https://getstream.io/winds/.” which is not a key-value pair, group, or comment

**Reproduces how often:** always

### Versions

2.1.0

**Comment by dashsd** [comment]
Same issue here on Arch Linux. Manually added the desktop entry with exec set to the "winds" executable file inside the app folder created in the temp directory. The desktop entry still doesn't register. Launching the app using the winds executable file (not the .AppImage file) does not produce the above error. Have set an environment variable to launch directly from terminal for now.

**Comment by jcamilom** [comment]
I'm working on this.

As @dashsd mentioned, the multi-line value for the key "description" in the "package.json" file is creating the issue. I'll make a PR soon.
