### ISSUE TITLE
Idea: Single User usage

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GetStream/Winds#44]
Actually Winds allows every user who knows the Url where the app is being hosted, to be used by everyone.

Would be cool to have the possibility to configure only one user, in order to make it more personal ( say you want to host this into your own website hosting space ).

Thank you in advance :)

**Comment by tschellenbach** [comment]
it's a solid idea. how would you like this to work in terms of configuration?

**Comment by julianxhokaxhiu** [comment]
I admit I have no real vision at the moment, but I'm pretty sure that it may escalate quickyl from 1 user to many, but still a closed circle.

I think we need to make sure that a first admin user with a random password at first setup is created.

Then afterwards is up to the user to add more or keep just one.

Of course an admin page where to manage them is required. Additional users may be added by inviting via email ( see Ghost ).
