### ISSUE TITLE
Podcast streams failing during playback

### ISSUE THREAD

**Issue by N-Upchurch** [GetStream/Winds#447]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Podcasts hang during playback and do not continue, even after scrubbing backwards, or pausing and unpausing. 

### Steps to Reproduce

1. Just play a podcast. 

**Expected behavior:** Podcast plays all the way through.

**Actual behavior:** Podcast pauses at some point and does not continue.

**Reproduces how often:** I have tried to play ~3 podcasts, and the issue has occurred during each.

### Versions

About Winds fails to produce dialog box.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tschellenbach** [comment]
Thanks for reporting this issue. Which version of Winds and what platform are you using?

**Comment by nparsons08** [comment]
Unable to reproduce. Likely a network issue. Will re-open once we know the version. Thank you!
