### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by batarian71** [GetStream/Winds#449]
Hi. I am a graphic designer. I would like to volunteer to design a logo for this repository that you can use in the readme file. What do you say?

**Comment by nparsons08** [comment]
Hey @batarian71! We have a dedicated designer on the project so we are all set on design for now. We do appreciate you reaching out. Given your experience, we'd love if you could provide some feedback on the design and ways that we can make it better. Looking forward to it! Cheers! 🎉
