### ISSUE TITLE
Bug: Sails errors cannot be logged if sentry.active=false

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GetStream/Winds#45]
I've found out that when you disable the `sentry.active` property inside [production.js](https://github.com/GetStream/Winds/blob/master/config/env/production.js#L2), when the code reaches [this line](https://github.com/GetStream/Winds/blob/master/api/controllers/AuthController.js#L127), for example, it just crashes.

Would be awesome if all around the code this check is being done, in order to just `console.log` if sentry is not being used.

Thanks in advance :)

**Comment by tschellenbach** [comment]
looks like this should just use sails.log.error
good point, will pick this up in one of the next versions

**Comment by tschellenbach** [comment]
Ideally we just use the logging system. @nparsons08 had some issues getting that to work though:
https://github.com/diegopamio/sails-hook-sentry/blob/master/index.js

**Comment by nparsons08** [comment]
Fixed in latest push - https://github.com/GetStream/Winds/commit/983b7abdf9832986d4fcf8ea68216146b9cf72fd

**Comment by nparsons08** [comment]
@julianxhokaxhiu 👍
