### ISSUE TITLE
StreamApiError

### ISSUE THREAD

**Issue by g0g11** [GetStream/Winds#450]
### Prerequisites

* [ x ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Wanted prepare my development environment to contribute on this project, but have an issue with the Stream API. The following error occurs if I try to signup:

```
0|api      |     at Request.EventEmitter.emit (domain.js:460:23)
0|api      |     at IncomingMessage.<anonymous> (/Users/username/Documents/Projects/Winds/api/node_modules/request/request.js:1079:12)
0|api      |     at Object.onceWrapper (events.js:273:13)
0|api      |     at IncomingMessage.emit (events.js:187:15)
0|api      |     at IncomingMessage.EventEmitter.emit (domain.js:460:23)
0|api      |     at endReadableNT (_stream_readable.js:1081:12)
0|api      |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|api      | Error: {"detail":"Empty payload","status_code":400,"code":4,"exception":"InputException","duration":"0.12ms"} with HTTP status code 400
0|api      |     at StreamApiError.ErrorAbstract (/Users/username/Documents/Projects/Winds/api/node_modules/getstream/src/lib/errors.js:20:11)
0|api      |     at new StreamApiError (/Users/username/Documents/Projects/Winds/api/node_modules/getstream/src/lib/errors.js:87:17)
0|api      |     at Request.task [as _callback] (/Users/username/Documents/Projects/Winds/api/node_modules/getstream/src/lib/client.js:206:16)
0|api      |     at Request.self.callback (/Users/username/Documents/Projects/Winds/api/node_modules/request/request.js:185:22)
0|api      |     at Request.emit (events.js:182:13)
0|api      |     at Request.EventEmitter.emit (domain.js:460:23)
0|api      |     at Request.<anonymous> (/Users/username/Documents/Projects/Winds/api/node_modules/request/request.js:1157:10)
0|api      |     at Request.emit (events.js:182:13)
0|api      |     at Request.EventEmitter.emit (domain.js:460:23)
0|api      |     at IncomingMessage.<anonymous> (/Users/username/Documents/Projects/Winds/api/node_modules/request/request.js:1079:12)
0|api      |     at Object.onceWrapper (events.js:273:13)
0|api      |     at IncomingMessage.emit (events.js:187:15)
0|api      |     at IncomingMessage.EventEmitter.emit (domain.js:460:23)
0|api      |     at endReadableNT (_stream_readable.js:1081:12)
0|api      |     at process._tickCallback (internal/process/next_tick.js:63:19)
1|conducto | info: conductor will schedule at most 1 of type rss to scrape per 60 seconds
1|conducto | info: found 0 popular publications of type rss that we scrape every 2 minutes and 0 that we scrape every 2 minutes
1|conducto | info: marked 0 of type rss publications as isParsing
1|conducto | info: conductor found 0 of type rss to scrape
1|conducto | info: Processing complete! Will try again in 60 seconds...
```
The .env file is created with all 4 variables (STREAM_APP_ID, REACT_APP_STREAM_APP_ID, STREAM_API_KEY and STREAM_API_SECRET) for getstream.io. The account on getstream.io is configured as described in the README.

### Steps to Reproduce

1. Clone the repository and setup the environment as described in README
2. Start API & APP
3. On Web or Electron try to signup as a new user

**Expected behavior:** Signup a new user

**Actual behavior:** Error occurs, and unable to register a new user

**Reproduces how often:** always 

### Versions

2.0.4 and also tried with 2.1.45

### Additional Information

-

**Comment by tschellenbach** [comment]
@nparsons08 is looking into this. im totally confused about it as well.

**Comment by tschellenbach** [comment]
@Nekuromento any idea about this?

**Comment by g0g11** [comment]
@tschellenbach so it's a known issue?

**Comment by tschellenbach** [comment]
Do you still see this issue in 2.1.46? @g0g11
I believe it's fixed.

**Comment by g0g11** [comment]
Hello @tschellenbach 
it's better but still not completely solved, I have right now the following issue if I try to signup with a new account:

1|conducto | info: Conductor iteration completed...
0|api      | interests:3:v2:1:46
0|api      | error: [object Object] Request failed with status code 500 Error: Request failed with status code 500
0|api      |     at createError (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/createError.js:16:15)
0|api      |     at settle (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/settle.js:18:12)
0|api      |     at IncomingMessage.handleStreamEnd (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/adapters/http.js:201:11)
0|api      |     at IncomingMessage.emit (events.js:187:15)
0|api      |     at IncomingMessage.EventEmitter.emit (domain.js:460:23)
0|api      |     at endReadableNT (_stream_readable.js:1081:12)
0|api      |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|api      | Error: Request failed with status code 500
0|api      |     at createError (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/createError.js:16:15)
0|api      |     at settle (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/settle.js:18:12)
0|api      |     at IncomingMessage.handleStreamEnd (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/adapters/http.js:201:11)
0|api      |     at IncomingMessage.emit (events.js:187:15)
0|api      |     at IncomingMessage.EventEmitter.emit (domain.js:460:23)
0|api      |     at endReadableNT (_stream_readable.js:1081:12)
0|api      |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|api      | error: [object Object] Request failed with status code 500 Error: Request failed with status code 500
0|api      |     at createError (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/createError.js:16:15)
0|api      |     at settle (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/settle.js:18:12)
0|api      |     at IncomingMessage.handleStreamEnd (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/adapters/http.js:201:11)
0|api      |     at IncomingMessage.emit (events.js:187:15)
0|api      |     at IncomingMessage.EventEmitter.emit (domain.js:460:23)
0|api      |     at endReadableNT (_stream_readable.js:1081:12)
0|api      |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|api      | Error: Request failed with status code 500
0|api      |     at createError (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/createError.js:16:15)
0|api      |     at settle (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/core/settle.js:18:12)
0|api      |     at IncomingMessage.handleStreamEnd (/Users/username/Documents/ProjectsWinds/api/node_modules/axios/lib/adapters/http.js:201:11)
0|api      |     at IncomingMessage.emit (events.js:187:15)
0|api      |     at IncomingMessage.EventEmitter.emit (domain.js:460:23)
0|api      |     at endReadableNT (_stream_readable.js:1081:12)
0|api      |     at process._tickCallback (internal/process/next_tick.js:63:19)

And also an error in the web console (check attachment).
![winds-error-500](https://user-images.githubusercontent.com/16637843/42415625-5556c5d6-8255-11e8-8f7c-bff73b7a35ba.png)

I am not sure, but I think I did everything right for the local environment. Maybe I missing something? Is the local environment in v2.1.46 working for you without any problems? 

I like the project, and also the stack, so I would like to contribute on this. But to start I would like to have my environment ready :(

**Comment by g0g11** [comment]
I think the problem is that my database has no collections except the users collection. Do you have any sample database data, so I can import it to my mongodb? @tschellenbach

**Comment by nparsons08** [comment]
Hi @g0g11, attached is a zip containing a MongoDB dump with RSS and Podcast data. It should have all of the collections you need as well. 

Please login with `test@test.com` with the password `test` for debugging. You can also create new users with this. 

You may need to run the `FLUSHALL` command in Redis to ensure that new RSS and Podcasts are cached.

Hope this helps!

[WINDS.zip](https://github.com/GetStream/Winds/files/2176765/WINDS.zip)

**Comment by nparsons08** [comment]
@g0g11 The 500 errors you were seeing in the screenshot above have been resolved in the latest release. Just pull and you should be all set :) 👍

**Comment by g0g11** [comment]
@nparsons08 the database is fixed, but the 500 error is still here ... Something is wrong in the get method in personalization/index.js :(

**Comment by nparsons08** [comment]
Hmm. The PR hasn't been merged yet. Working on that now – maybe it'll fix the issue you're seeing.

**Comment by g0g11** [comment]
@nparsons08 okey will check it later or tomorrow ...

**Comment by nparsons08** [comment]
@g0g11 An update has been merged. Can you verify if this fixes your issue? Thank you!

**Comment by g0g11** [comment]
@nparsons08 good job!

**Comment by nparsons08** [comment]
Awesome! I assume that fixes the issue. 😄 I'm going to close this out, however, feel free to open another issue should something arise. Happy coding! 🎉
