### ISSUE TITLE
Bug: Csrf issue prevents to reset the password if the app crashes ( restarted by PM2 )

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GetStream/Winds#46]
I found out that if for some reasons the application crashes during an API processing ( say Password Reset ), the CSRF token prevents the user to use any other call to the Winds app.

Therefore a way to handle this situation should be possible. As of today, the only way to fix this is by clearing the localStorage and/or related Cookies.

Thanks in advance :)

**Comment by nparsons08** [comment]
@julianxhokaxhiu -- Potential fix: Setup a Redis instance as your session store.

**Comment by julianxhokaxhiu** [comment]
Is there already an ENV for that? So I could improve the dockerfile :)

Thanks in advance

**Comment by nparsons08** [comment]
@julianxhokaxhiu Just pushed up an update to the `.env_example` file. Let me know if you have any questions. Do note that the updated code requires a Redis instance. The password for Redis can be configured in the `.env` file.
