### ISSUE TITLE
Bug: Imported feeds don't load

### ISSUE THREAD

**Issue by hyperfekt** [GetStream/Winds#47]
I imported an OPML file from Inoreader and it turns out that the subscriptions simply keep loading forever, never retrieving any items. Subscribing to that same existing feed again manually fixes the issue.

**Comment by tschellenbach** [comment]
Thanks for reporting this issue, it's very likely related to:
https://github.com/GetStream/Winds/issues/34

**Comment by nparsons08** [comment]
@tschellenbach @hyperfekt The issue has been confirmed. It is because the import script is not returning a response when it completes the import. Thank you for the heads up, @hyperfekt.
