### ISSUE TITLE
Blank app

### ISSUE THREAD

**Issue by dcalano** [GetStream/Winds#472]
When clicking a search suggestion, occasionally the entire app will turn blank

**Comment by nparsons08** [comment]
@dcalano If this happens again, do you mind posting your search query or the full URL in here? It will help me replicate and fix. Thank you for bringing this to our attention!

**Comment by dcalano** [comment]
Sure. I will post an update later today. I am using Winds via the OS X desktop application but I can post a video/screenshots of the behavior

**Comment by daniglezad** [comment]
This has happened to me regardless of what you search. **Either you click or press enter**, the app turns blank and you need to restart it to operate normally (until it happens again).

**Comment by nparsons08** [comment]
A resync of the search index likely fixed this. Please reopen if the issue persists.

**Comment by brttnylrnsstuff** [comment]
I have the same issue, and it is happening 100% of the time after clicking on a link or adding a new feed. I am using the web version on Mac OS X.
