### ISSUE TITLE
Sign Up? Really?!?!

### ISSUE THREAD

**Issue by markentingh** [GetStream/Winds#479]
I am sick of finding apps where I have to sign up and share my data on some remote server. This is an RSS feed app, not a web service! I want to keep my data local on my hard drive without the need to sign up or log into your web service. Please fix this serious issue.

**Comment by nparsons08** [comment]
Sorry, this app requires sign in because we offer personalized feeds. It's 100% open-source, so you're welcome to clone the code and create a version for yourself that is on your machine.

**Comment by tschellenbach** [comment]
Biggest issue is that you can't do a pure local version & support mobile.

**Comment by nparsons08** [comment]
@markentingh Regarding what @tschellenbach said, that is a pretty big issue. We require users to signup/login so that we can maintain state across all variations of the application (e.g. native, web, and mobile).

**Comment by markentingh** [comment]
Definitely all very good points... would be nice though to also have an option to ignore all those points and just use the app without requiring a signup process.
