### ISSUE TITLE
Filters and folders question. 

### ISSUE THREAD

**Issue by sasnfbi1234** [GetStream/Winds#480]
I looked around and can't tell. I still use the old af 'RSS Owl' because it has 1.Filters and 2.Folders so I can sort content. I want to switch to this but as far as I can tell it does not have these features. please let me know if im missing something on either front. Or if not how hard would it be to add them?

**Comment by nparsons08** [comment]
Hey @sasnfbi1234, this isn't something that is currently supported; however, we do have plans to implement this functionality in the near future. Cheers!
