### ISSUE TITLE
How do I deploy to AWS?

### ISSUE THREAD

**Issue by vincentroman** [GetStream/Winds#485]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from the manu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by tschellenbach** [comment]
That would be awesome, guides on how to deploy winds on AWS, DO, Google, Kubernetes, Zeit etc.
I like it

**Comment by vincentroman** [comment]
yes it will really be helpful

**Comment by vincentroman** [comment]
sorry please i will prefer vanilla thank you.

**Comment by nparsons08** [comment]
I'll write up a tutorial here in the next couple of days for you. Sorry for the delay.

**Comment by vincentroman** [comment]
ok thanks please can you be i bit specific please cus i am using it for my school project which i should be done with by Sunday evening so if maybe you can help maybe write one before sunday i will really appreciate your effort as always thanks for your reply

**Comment by vincentroman** [comment]
either way i will be waiting

**Comment by nparsons08** [comment]
Hey @vincentroman, we haven't had a chance to get around to it – apologies. Is there something in particular that you are struggling with?

**Comment by vincentroman** [comment]
yes am finding it hard to upload wind and cabin on DO, AWS, or google cloud however i have managed to host the cabin app on digital ocean but its not working with https in particular i cant host the cabin app and wind with https i whant to know how tohost it with https

**Comment by vincentroman** [comment]
How do I deploy it with https on digitalocean or google cloud

**Comment by vincentroman** [comment]
please i know you're busy but please show me how to use it on docker instead i am really relying on it to continue with the learning of my project thanks

**Comment by nparsons08** [comment]
Hi @vincentroman, we will have a tutorial for both the API and frontend available tomorrow. Thank you for your patience.

**Comment by nparsons08** [comment]
@vincentroman, the following posts will help you deploy to AWS. Be sure to follow closely. Thank you.

https://getstream.io/blog/deploying-the-winds-api-to-aws-ecs-with-docker-compose/

AND

https://getstream.io/blog/deploying-the-winds-app-to-amazon-s3-and-cloudfront/

**Comment by vincentroman** [comment]
Thanks a lot I know this is closed but will this works on google cloud and can I apply it the cabin app?

**Comment by nparsons08** [comment]
Cabin and Winds are completely separate applications. Both will take knowledge of basic DevOps skills to get up and running in your own environment. We no longer support Cabin, therefore we don't have any intentions to create an updated tutorial for it.

**Comment by nparsons08** [comment]
Additionally, this is meant for AWS and not Google.

**Comment by vincentroman** [comment]
Ok thank you very much

**Comment by vincentroman** [comment]
@nparsons08 please i know this of topic and u are definitely not concerned about this but please i am having issues with my cabin app api, the issue there is that am getting an error stating that cors on the same domian in not allowed

**Comment by vincentroman** [comment]
it ddoes not allow app to push data to api please help me thanks
