### ISSUE TITLE
Pressing escape on an article view should bring back to the list

### ISSUE THREAD

**Issue by borisrorsvort** [GetStream/Winds#486]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Pressing escape on an article view doesn’t do anything

### Steps to Reproduce

1. Go to your Rss feeds list
2. Click on an article
3. Press escape

**Expected behavior:** Go back to the feed

**Actual behavior:** Void

**Reproduces how often:** Always

### Versions

2.1.90

**Comment by nparsons08** [comment]
Good thought here. We'll need to do some basic keybinding here, so it shouldn't be too difficult. Are you up for a coding challenge by chance?

**Comment by borisrorsvort** [comment]
You mean submit a PR for this? I’ll try to find the time to have a look. Do you already have something in mind to handle keybinding?

Following http://www.npmtrends.com/react-hotkeys-vs-react-keybinding-vs-react-keybinding-component-vs-react-shortcuts it seems react-hotkeys is the wizer option.
