### ISSUE TITLE
Mark as read option missing

### ISSUE THREAD

**Issue by borisrorsvort** [GetStream/Winds#487]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I am missing a «Mark all as read» option somewhere (global or per feed)
Also If I go to an article and press back, it doesnt remove the green dot which I suppose is the read indicator

**Comment by nparsons08** [comment]
Thank you @borisrorsvort! We'll add this to our backlog and address it as soon as possible! Keep the feedback coming :) 👍

**Comment by nparsons08** [comment]
@AminMahboubi We have an endpoint for handling this. Ping me if you need direction.

**Comment by AminMahboubi** [comment]
@nparsons08 Could you send me the endpoint?

**Comment by TobiasDev** [comment]
Did this get added? Or was there a decision to not have a mark for read option?

**Comment by mahboubii** [comment]
Currently the green indicator is set for recent articles, it's not actually a not yet read sign. however we probably will add this feature to the frontend as Stream already support this

**Comment by TobiasDev** [comment]
> 
> 
> Currently the green indicator is set for recent articles, it's not actually a not yet read sign. however we probably will add this feature to the frontend as Stream already support this

That would be awesome! I just want to be able to see which ones are new and which one I just didn't want to read. Because it seems like the green dot never goes away.

**Comment by TobiasDev** [comment]
Is there any status on this?

**Comment by mahboubii** [comment]
@TobiasDev unfortunately no dev yet.

**Comment by nayabbashasayed** [comment]
I really like Winds. I like the snap app and I like my subscriptions synced to the cloud.

The only thing stopping me from using it over other podcast/rss app is the "Mark as read" option missing.

Is there anyway I can mark my articles or podcasts as read?

**Comment by marshalleq** [comment]
Yes, I accidentally discovered this app, after searching for Feedly open source server alternatives.  Auto mark as read (while scrolling) or similar is definitely #1 on my Wishlist, for me I can't actually use an app that doesn't have this otherwise I just end up looking at the same stuff over and over.  Unless, there's some other way of handling that?  Could do some kind of a 'viewed to here' as an option.
