### ISSUE TITLE
Missing way to go back to all feeds when viewing a specific source feed

### ISSUE THREAD

**Issue by borisrorsvort** [GetStream/Winds#488]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

There is no way to go back to all feeds when seing a particular feed, you need to go to home and then «View all»

<img width="640" alt="winds - powered by getstream io 2018-08-17 09-26-26" src="https://user-images.githubusercontent.com/39081/44253401-ca71fb00-a1ff-11e8-99d4-d90e7fa5cef6.png">

**Comment by nparsons08** [comment]
Thank you @borisrorsvort! We'll add this to our backlog and address it as soon as possible! Keep the feedback coming :) 👍

**Comment by nparsons08** [comment]
@AminMahboubi Please work with Josh on a spec for this.
