### ISSUE TITLE
Building for the AUR

### ISSUE THREAD

**Issue by kyledolichev** [GetStream/Winds#490]
Hi, I'd like to build your app for the AUR, but I am unsure of how exactly to package this app.

so far this is what I've got

```
pkgname=Winds
pkgver=2.1.143
pkgrel=1
pkgdesc='Podcasts and RSS feeds in one app'
arch=(x86_64)
url='getstream.io/winds/'
license=BSD-3-Clause
depends=(redis mongodb)
makedepends=(yarn pm2)
source=("https://github.com/GetStream/${pkgname}/v${pkgver}.tar.gz")
sha512sums=('9caced2e2fb764b0c9cdb8667a6b51a21198d59f55466bdd5c8dbb516b4d6994ff5d6de5ddec955099a7c40ca8c98f10fd979b1af12e9f38a02bb3111596d2f3')

prepare() {
        yarn global add babel-cli
}

build() {
        cd api
        yarn
        cd ../app
        yarn
}

package() {

}

```

any idea how I would get this into a package? What files should be installed to the system and are there any dependencies I am missing? Not a fan of AppImages, would be nice if you guys supported flatpak, but ultimately I'd like this to run natively.

**Comment by nparsons08** [comment]
I'm not too familiar with AUR but are you opposed to installing with snap?

1. `yaourt -S snapd`
2. `sudo systemctl enable --now snapd.socket`
3. `sudo snap install winds`

**Comment by kyledolichev** [comment]
I don't use systemd, IDK if I can even use snap tbh. I'd like to get this running natively so it can be posted to the AUR, once I figure this out I can also package it for Void Linux. I don't think snap is available on Void MUSL either, so snap won't do. Flatpak would work but not snap or AppImage.

**Comment by kyledolichev** [comment]
Do you know how I can install this into a package? I've never seen anyone use yarn before for anything.

**Comment by nparsons08** [comment]
I'm really not sure. I asked around the team and did a bit of research. Doesn't look like electron builder (the package we use to build for linux) supports your package type. Very sorry.
