### ISSUE TITLE
Provide design files for contributors

### ISSUE THREAD

**Issue by borisrorsvort** [GetStream/Winds#491]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I guess It will be easier for contributors to suggest Ui changes if they can start from an up to date design file (sketch) or project (Figma),...

We could always screenshot, but it would be nice to be able to reuse some existing components if any.

**Comment by nparsons08** [comment]
Hey @borisrorsvort, we need to do a bit of cleanup on the Sketch file prior to releasing it to the community. Another round of design will be starting shortly so we'll release it once the new features are in place. Thanks for the issue! Cheers!
