### ISSUE TITLE
Display unread count pills to Rss Box

### ISSUE THREAD

**Issue by borisrorsvort** [GetStream/Winds#492]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I would be helpfull to display a total unread count in the box header as well as on the list items.

![unread](https://user-images.githubusercontent.com/39081/44282815-8d882180-a25c-11e8-88d6-c9b1d78b480d.png)

**Comment by nparsons08** [comment]
Closing this out due to inactivity.

**Comment by borisrorsvort** [comment]
?? Don’t you think it should be there? Wasn’t this planned in https://github.com/GetStream/Winds/issues/491#issuecomment-414381818 
A rss reader without unread count is pretty useless...
