### ISSUE TITLE
Feeds haven't updated since I followed them, although they should have

### ISSUE THREAD

**Issue by zaluzianskya** [GetStream/Winds#494]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I just installed Winds, eager for a joint RSS and podcast app, but even though some of the feeds I'm following _should_ have updates since I followed them, they don't.

The feeds this is happening with:

Saturday Morning Breakfast Cereal - https://www.smbc-comics.com/comic/rss
Several options show up when searching this title; one in Russian, one in French, one that says "updated daily" but has no articles underneath it, and one that causes the screen to go blank upon clicking; the one I'm following is the second option in the dropdown, with the purpleish icon next to it, and although there was a new comic today, the most recent entry in the feed is from 2 days ago.

Archive of Our Own tag feeds - One example: https://archiveofourown.org/tags/796030/feed.atom
Although I added this feed yesterday, Winds still shows no entries. I have no problem following this feed and others like it in other RSS apps.

(If this is happening with other feeds I'm following then I'm not aware of it, because they haven't had new content posted since I started following them.)

### Steps to Reproduce

1. Follow one of the feeds in question
2. Observe lack of updates

**Expected behavior:** Feeds should update within a few minutes, maybe an hour, of new content being posted.

**Actual behavior:** Feeds do not update.

**Reproduces how often:** 100%

### Versions

Don't know, because clicking on File > About doesn't do anything. I'm using Ubuntu 18.04.1 LTS and installed the latest version from the Ubuntu Software Center.

**Comment by tschellenbach** [comment]
How about now?

**Comment by zaluzianskya** [comment]
They have updated now.
