### ISSUE TITLE
Auto update the app without having to manually a new version

### ISSUE THREAD

**Issue by borisrorsvort** [GetStream/Winds#497]
This could help: https://github.com/electron/electron/blob/master/docs/api/auto-updater.md

**Comment by nparsons08** [comment]
Hey @borisrorsvort, we rely on the app stores to handle updates on our end so if it's a self-downloaded version, you're going to have to keep up with our updates for now. Auto updates for self-serve versions aren't currently in the pipeline. Thanks!
