### ISSUE TITLE
Download blocked by Windows Defender

### ISSUE THREAD

**Issue by Nkoyan** [GetStream/Winds#498]
I downloaded the app with chrome on Windows 10 and got this :
![aaa](https://user-images.githubusercontent.com/18040372/44909880-f66da000-ad18-11e8-892d-e0749e4e27b6.PNG)

**Comment by nparsons08** [comment]
HI @Nkoyan, this is something that we've seen before and aren't quite sure why it's being blocked. We'll continue to work on the issue on our end. Thank you for reporting.

**Comment by nparsons08** [comment]
@Nkoyan are you able to bypass this in any way?
