### ISSUE TITLE
Idea: Import feeds, tags, saves, and folders from Feedly

### ISSUE THREAD

**Issue by balupton** [GetStream/Winds#5]
Since Google Reader died, I imported all my data from it to Feedly, now that this is out, would be cool to import all that data into this.

**Comment by icnagy** [comment]
👍 Or just add Feedly login and sync?

**Comment by nparsons08** [comment]
@balupton @icnagy Great ideas, however, Feedly doesn't look to be handing out API access at this time. They're a bit behind on their v2 API launch.

"Update: We are in the process of creating the second iteration of the feedly API. The ETA is Q2 2016. We will NOT be delivering production keys between now and then. If you have an urgent request, please contact support@feedly.com"

More here: https://developer.feedly.com/

Any thoughts? Open to a PR. :)

**Comment by icnagy** [comment]
@nparsons08 Oh, I missed that. In that case: OPML import? I guess that could be the base for Feedly import once they catch up.

**Comment by nparsons08** [comment]
For reference: https://www.cnet.com/how-to/how-to-export-feedly-subscriptions-to-opml/

**Comment by nparsons08** [comment]
@icnagy @balupton You can now import OPML files into Winds. When logged in, navigate to Subscriptions and on the bottom left of the page you'll see an option to Import OPML. We've tested this against a couple Feedly exports. Please let us know if you run into any issues. Thank you!

**Comment by mattpanther** [comment]
Is importing from OPML still an option? I'm not seeing a subscriptions area. When I go to RSS and look at all feeds I don't see an option to import, also don't see it in the profile settings anywhere. Thanks for any tips!

![image](https://user-images.githubusercontent.com/22131722/40577338-175ab43a-60d2-11e8-8e53-58ec780ecbb2.png)

**Comment by tschellenbach** [comment]
yes, click new, select rss, click import OPML

we're going to change the design for this, cause its not really easy to find. sorry about that!
