### ISSUE TITLE
Winds Won't stream episodes

### ISSUE THREAD

**Issue by chungsie** [GetStream/Winds#520]
Winds will not play podcasts/episodes. Some episodes never play. I've tried refreshing the list, and restarting system. I'm on Ubuntu 18.04. THere seems to be no relevant tips on how to solve this in google.

**Comment by nparsons08** [comment]
Can you let us know what episodes you are referring to so that we can look into the issue? We need some kind of context to go by when debugging.

**Comment by chungsie** [comment]
Bad At Sports episodes not titles Episode, and the latest two.

**Comment by roberthchan** [comment]
Hi im using MacOSX, the dmg works great, but in chrome 69 not play the audios, i use using RSS in **Ivoox** (not play) and sometimes **Spreaker** (works fine), When i clic on Podcast menu, show me random episodies (not only the options choiced).
