### ISSUE TITLE
Version 2.3.1 installed via Snap doesn't work on Ubuntu 16.04

### ISSUE THREAD

**Issue by antonfefilov** [GetStream/Winds#529]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

App has a blank screen after starting.

### Steps to Reproduce

1. Install it via Snap
2. Run it.
3. Enjoy the blank screen :)

**Reproduces how often:** 100%

### Versions

2.3.1

### Additional Information

![image](https://user-images.githubusercontent.com/1530097/47253202-58b56800-d461-11e8-8f9c-e2e0a366582b.png)

**Comment by siwday** [comment]
I have the same problem on Debian.
Then I found there is a appImage version on the https://getstream.io/winds/ .So far so good

**Comment by nparsons08** [comment]
@antonfefilov for now, please use the `appImage` when possible. We're actively working to improve the Snap experience. Sorry for the inconvenience. On a positive note, some awesome features will soon be released!

**Comment by nparsons08** [comment]
Closing this out due to inactivity.

**Comment by dggonzalez1971** [comment]
have the same problem in
-Ubuntu 18.10
Snap
