### ISSUE TITLE
Discussion: Winds v0.3.0

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#53]
Here are some items we're considering for Winds 0.3:

- [x] Improvements to ranking algorithm
- [x] Sharing via Buffer
- [x] Suggested feeds: https://github.com/GetStream/Winds/issues/37
- [x] Social auth (Facebook)
- [x] Explicit upvotes: https://github.com/GetStream/Winds/issues/29

Let us know what changes you'd like to see for Winds!

**Comment by hyperfekt** [comment]
I'd love to be able import the news articles from my Twitter retweets, as I've already built a humongous profile of content I'm interested in there, and many others certainly too.
