### ISSUE TITLE
Install from source

### ISSUE THREAD

**Issue by LinArcX** [GetStream/Winds#530]
Hi. i want to create a pkgbuild for winds for arch linux. but i don't know how to do that.
Can you explain steps to follow for installation from source?

**Comment by nparsons08** [comment]
@LinArcX The app is an Electron build so I'm not 100% sure how to grab what you're looking for. What is the archive you're looking for to turn it into a `pkgbuild`? I may be able to export to that and send it your way.

**Comment by nparsons08** [comment]
Closing this out due to inactivity.
