### ISSUE TITLE
listen EADDRINUSE <PORT>, all ports giving this error

### ISSUE THREAD

**Issue by francishero** [GetStream/Winds#533]
Error: listen EADDRINUSE 8080 # This can remain as is
0|api    |     at Server.setupListenHandle [as _listen2] (net.js:1343:19)
0|api    |     at listenInCluster (net.js:1401:12)
0|api    |     at Server.listen (net.js:1496:5)
0|api    |     at Function.listen (/root/var/www/znewsly/api/dist/node_modules/express/lib/application.js:618:24)
0|api    |     at Object.<anonymous> (/root/var/www/winds/api/dist/server.js:114:6)
0|api    |     at Module._compile (module.js:653:30)
0|api    |     at Object.Module._extensions..js (module.js:664:10)
0|api    |     at Module.load (module.js:566:32)
0|api    |     at tryModuleLoad (module.js:506:12)
0|api    |     at Function.Module._load (module.js:498:3)
0|api    |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:48:21)
0|api    |     at Module._compile (module.js:653:30)
0|api    |     at Object.Module._extensions..js (module.js:664:10)
0|api    |     at Module.load (module.js:566:32)
0|api    |     at tryModuleLoad (module.js:506:12)
0|api    |     at Function.Module._load (module.js:498:3)
0|api    |     at Function.Module.runMain (module.js:694:10)
0|api    |     at startup (bootstrap_node.js:204:16)
0|api    |     at bootstrap_node.js:625:3

This error keeps coming even if i change the port, is there something am missing? am following this tutorial to deploy the api on digital ocean https://getstream.io/blog/deploying-the-winds-api-to-digital-ocean-with-fabric/

**Comment by nparsons08** [comment]
Are you experiencing this during every deploy? Have you attempted to restart the server?

**Comment by francishero** [comment]
@nparsons08 yes on every deploy, the worst is am actually experiencing it on my Windows machine where I hacked the npm scripts to run without pm2. so this is not problem with with pm2 but I can't figure out what's going on

**Comment by francishero** [comment]
@nparsons08 it happens on a fresh digital ocean Ubuntu 16.04 server, even on my local dev on Windows where am not using pm2

**Comment by francishero** [comment]
Ok so i fix this error by replacing some lines in api.listen() in the api/src/server.js. Not permanent solution but error is gone
