### ISSUE TITLE
ioredis: ReplyError: ERR DB index is out of range

### ISSUE THREAD

**Issue by francishero** [GetStream/Winds#534]
Am connecting to a local instance of redis, i keep getting this error, googling isnt helping

(node:28488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
0|api      | ReplyError: ERR DB index is out of range
0|api      |     at parseError (/root/var/www/znewsly/api/dist/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
0|api      |     at parseType (/root/var/www/znewsly/api/dist/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
0|api      | (node:28877) UnhandledPromiseRejectionWarning: ReplyError: ERR DB index is out of range
0|api      |     at parseError (/root/var/www/znewsly/api/dist/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:179:12)
0|api      |     at parseType (/root/var/www/znewsly/api/dist/node_modules/ioredis/node_modules/redis-parser/lib/parser.js:302:14)
0|api      | (node:28877) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
0|api      | (node:28877) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ORESoftware** [comment]
@francishero next time you close an issue why don't you tell people how you resolved it thanks
