### ISSUE TITLE
Absence of a couple of env variables in the sample .env file provided in README.

### ISSUE THREAD

**Issue by lunaticmonk** [GetStream/Winds#535]
### Prerequisites

*Put an X between the brackets on this line if you have done all of the following:
    [x] Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

[Description of the issue]

### Steps to Reproduce

**Expected behavior:** [What you expect to happen]
The absent env variables have to be included in the sample .env provided in README.

**Actual behavior:** [What actually happens]
Currently, the .env file that is provided in README has a couple of env vars absent which are required when setting up the project locally. I experienced it when I tried to set up the project.

Those are:
`REACT_APP_STREAM_API_KEY`
`REACT_APP_STREAM_ANALYTICS`

**Comment by nparsons08** [comment]
@lunaticmonk Addressed. Thank you!
