### ISSUE TITLE
Icon missing on AppImage

### ISSUE THREAD

**Issue by shamilsherhan** [GetStream/Winds#538]
### Description

The app icon is missing both on the launcher and window header of the Winds AppImage

**Expected behavior:** The Winds icon to be displayed
**Actual behavior:** A blank file icon appears

**Reproduces how often:** 100%

### Versions

2.1.90

### Additional Information

![screenshot_20181102_052620](https://user-images.githubusercontent.com/20861048/47886570-e2e9cd00-de60-11e8-8872-bd4caaf42f91.png)
![screenshot_20181102_052733](https://user-images.githubusercontent.com/20861048/47886572-e3826380-de60-11e8-89d0-2117259d83f0.png)

**Comment by wetterSpitze** [comment]
@shamilsherhan i have the same problem on kubuntu 18.04.

as a workaround i have changed the `$HOME/.local/share/applications/appimagekit-winds.desktop` and placed my own `icon=<path>` in the file. But that just works for application menu not for dock-panels like Latte.

**Comment by mahboubii** [comment]
@shamilsherhan @wetterSpitze It is probably fixed in recent electron-builder updates. 
could you install winds latest version and confirm if the issue still exists?

https://s3.amazonaws.com/winds-2.0-releases/latest.html
https://snapcraft.io/winds

**Comment by mahboubii** [comment]
Launcher icon and application icon both exists on Winds v3.1.0 Ubuntu 18.10.
This might be OS related problem or due to using an old version of Winds.
