### ISSUE TITLE
Winds is unable to add a feed

### ISSUE THREAD

**Issue by rafifos** [GetStream/Winds#546]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I'm unable to add the [Intoxi Anime](https://www.intoxianime.com/feed/) feed, it's a feed generated by Wordpress.

### Steps to Reproduce

1. Try to add this RSS: https://www.intoxianime.com/feed/
2. Winds is unable to add it, "Oops, something went wrong..."

NOTE: There are some 500 erros on the console, not sure if it's related.

**Expected behavior:** The field is added and populated on Winds

**Actual behavior:** The "Oops" message is shown on the "Add RSS" dialog.

**Reproduces how often:** 100%

### Versions

Winds 2.3.4 (3.0.0 isn't available to install on the website at this time)

### Additional Information

--

**Comment by mahboubii** [comment]
If you change the protocol from `HTTPS` to `HTTP` it will pass this step. However, it won't parse any episode of the feed.
