### ISSUE TITLE
Allow HTTP caching

### ISSUE THREAD

**Issue by begriffs** [GetStream/Winds#547]
RSS clients typically include HTTP headers such as [If-Modified-Since](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/If-Modified-Since) in their requests which allows web servers to send back an empty body and status 304 if nothing has changed since the last check. Winds does not appear to send these kind of headers, which forces servers to waste bandwidth replying with the full RSS feed every time.

**Comment by mahboubii** [comment]
Thank you @begriffs, are you up for some coding? you could create a PR for this feature.

**Comment by begriffs** [comment]
Here's the crux: [ReadURL](https://github.com/GetStream/Winds/blob/6a9631fbf796e3b52e7a4418219741fdf969f6a1/api/src/parsers/feed.js#L206-L210) is passing only "User-Agent," "Accept-Encoding," and "Accept" headers.

Adding a `lastRequested` parameter to [ParseFeed](https://github.com/GetStream/Winds/blob/6a9631fbf796e3b52e7a4418219741fdf969f6a1/api/src/parsers/feed.js#L52) would probably be a good way to provide the context needed for setting the if-modified-since header in ReadURL.

But as for making a PR, aw hell naw -- I'm not setting up my dev environment for this javascript work of art.

**Comment by begriffs** [comment]
(Sorry, I regret my snark about javascript. I do hope someone is motivated to improve the http efficiency of Winds, but getting the dev tooling set up on my machine is more than I personally want to invest right now.)
