### ISSUE TITLE
AppImage Fails when   "No" to "integrate...?"

### ISSUE THREAD

**Issue by aplatypus** [GetStream/Winds#550]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Winds doesn't run when answered "No" to the "Would you like to integrate ...?" question.

### Steps to Reproduce

1. I double clicked on the AppImage file
2. "Install" pop-up comes up
3. I responded by pressing [NO] button.
4. Dialogue vanishes
5. Winds does not run

**Expected behavior:** [What you expect to happen]

The dialogue leds me to believe that I don't need to integrate the program (since I'm just testing it from ~/Downloads -- I would NOT be integrating.

> If you don't do this you can still launch the application by double-clicking on the AppImage.

**Actual behavior:** [What actually happens]

Well you can't "still launch..."

**Reproduces how often:** 100%

### Versions

You can get this information from the manu. Winds > About Winds.

- Winds-2.1.90-x86_64.AppImage with your system?

### Additional Information

This is Ubuntu 18.10, 64-bit, Cinnamon desktop.

**Comment by mahboubii** [comment]
@aplatypus Could you add more details/screenshots? 
you could also test on the latest version: 
https://s3.amazonaws.com/winds-2.0-releases/latest.html
https://snapcraft.io/winds

**Comment by aplatypus** [comment]
```
 $ chmod u+x ~/Downloads/Winds-2.1.90-x86_64.AppImage 
 $ ~/Downloads/Winds-2.1.90-x86_64.AppImage
```

![image](https://user-images.githubusercontent.com/67028/48924083-8ed68380-ef08-11e8-98a6-9f6f57b70a80.png)

```
 $ ~/Downloads/Winds-2.1.90-x86_64.AppImage
 $ #  click [NO] button.
Segmentation fault (core dumped)

```

So no:
- s3.amazonaws.com/winds-2.0-releases/latest.html
snapcraft.io/winds

Failed.
