### ISSUE TITLE
Closing the app interrupts any playing podcast

### ISSUE THREAD

**Issue by tkrugg** [GetStream/Winds#560]
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description
When I hit close, the app should fade out of sight but still run in the background and my podcast to keep playing.
This is unusual to most music players out there (I'm thinking deezer, spotify, itunes)

![2018-12-18 16 02 14](https://user-images.githubusercontent.com/2982512/50162323-5a26d380-02de-11e9-8a33-05a1f3e242cd.gif)

### Steps to Reproduce

1. Start the App
2. Start any podcast
3. Close the app 
![image](https://user-images.githubusercontent.com/2982512/50162470-bf7ac480-02de-11e9-8c7c-223c7c28925a.png)

**Expected behavior:** 
- the podcast should keep playing
- the app should keep running

**Actual behavior:** [What actually happens]
- the podcast stops playing
- the app stops running, and you have to start it again

### Versions

- 3.1.3 (on macOS High Sierra)

### Additional Information

none

**Comment by nparsons08** [comment]
@tkrugg Interesting. We don't have background support in place but if you minimize, that's an option. We're value open-source contributions if you'd like to get your hands dirty with Electron :) I'd be happy to review and accept your PR.

**Comment by mahboubii** [comment]
Addressd in https://github.com/GetStream/Winds/commit/a8fe387c0c16530e7aca1885f2272dc0ddd2184c
Released in V3.1.5
@tkrugg you can download the latest version here: https://s3.amazonaws.com/winds-2.0-releases/latest.html
