### ISSUE TITLE
Unable to create a new record in a algolia index

### ISSUE THREAD

**Issue by sejpalkalpesh** [GetStream/Winds#565]
### Prerequisites

* [X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues
Thanks a lot for this beautiful tool!
### Description

Unable to create a new record in algolia index

### Steps to Reproduce

1. Instal winds API in GCP ubuntu server 16.04 using guide https://getstream.io/blog/deploying-the-winds-api-to-digital-ocean-with-fabric/
2. [Start it in dev envirment ]

**Expected behavior:** New records inserted in a algolia index

**Actual behavior:** Unable to add new records in a algolia index

**Reproduces how often:** I try it more than 5 times in different environment but no solution 

### Versions

Winds v3.1.6

**Comment by nparsons08** [comment]
@sejpalkalpesh I'm not 100% sure what's going on from that error log. There's nothing that is related to Algolia that I can see. I am concerned that your MongoDB username and password are showing. Please change your MongoDB password as soon as possible! I would suggest providing an output with console logs that have your Algolia output (e.g. error messages, etc.).

**Comment by sejpalkalpesh** [comment]
thanks for your concern I will provide you another log with batter details. And I'll delete that user soon in MongoDB

**Comment by GeorgeWillaman** [comment]
Just checking in. Having the same issue, any ideas?

**Comment by sejpalkalpesh** [comment]
![capture](https://user-images.githubusercontent.com/46150285/51051617-585ce100-15fa-11e9-833c-247a3d0bffa9.JPG)
![capture2](https://user-images.githubusercontent.com/46150285/51051618-585ce100-15fa-11e9-8bca-3eda7dd812fa.JPG)
![capture3](https://user-images.githubusercontent.com/46150285/51051619-58f57780-15fa-11e9-8e4e-297cf86d15fd.JPG)
please check this photos so you can understand my problem.

**Comment by sejpalkalpesh** [comment]
there is no record in algolia index so no data in search.
![capture4](https://user-images.githubusercontent.com/46150285/51051928-357efc80-15fb-11e9-8a7d-945450427f51.JPG)

**Comment by sejpalkalpesh** [comment]
@nparsons08 Sorry but still same issue no changes in error.

**Comment by nparsons08** [comment]
@sejpalkalpesh Do you mind pasting your `.env` file in here? Make sure to pull out any sensitive information, please.

**Comment by sejpalkalpesh** [comment]
DATABASE_URI=mongodb+srv://<username>:<password>@<??>.gcp.mongodb.net/test?retryWrites=true
CACHE_URI=redis://localhost:6379
JWT_SECRET=<randome number>
NODE_ENV=prod
API_PORT=8080
REACT_APP_API_ENDPOINT=https://api.plusios.com
STREAM_API_BASE_URL=https://windspersonalization.getstream.io/personalization/v1.0
STREAM_APP_ID=<>
STREAM_API_KEY=<>
STREAM_API_SECRET=<>
REACT_APP_STREAM_APP_ID=<>
REACT_APP_STREAM_API_KEY=<>
REACT_APP_STREAM_ANALYTICS=<>
REACT_APP_ALGOLIA_APP_ID=8KGVQL6KRG
REACT_APP_ALGOLIA_SEARCH_KEY=<>
ALGOLIA_WRITE_KEY=<>
MERCURY_KEY=<>
REACT_APP_GOOGLE_ANALYTICS=<>

**Comment by sejpalkalpesh** [comment]
![capture5](https://user-images.githubusercontent.com/46150285/51055656-821c0500-1606-11e9-953d-e0bf1de94a0b.JPG)
there are some errors but I couldn't identify it.

**Comment by GeorgeWillaman** [comment]
Is your .env file missing?

**Comment by sejpalkalpesh** [comment]
It's in "app" folder.

**Comment by GeorgeWillaman** [comment]
Copy it and put another .env in api/test

**Comment by sejpalkalpesh** [comment]
![capture6](https://user-images.githubusercontent.com/46150285/51055955-7ed54900-1607-11e9-8653-f37db216753c.JPG)
Still same issue!!

**Comment by GeorgeWillaman** [comment]
Just go the root directory, cd into app. Why did you cd into .env test/

**Comment by sejpalkalpesh** [comment]
thanks, solver it by setting up NODE_ENV but still no solution there is still no solution.
![capture7](https://user-images.githubusercontent.com/46150285/51056633-51899a80-1609-11e9-8173-863a0b96ae1e.JPG)

**Comment by sejpalkalpesh** [comment]
please check error from www.plusios.com

**Comment by GeorgeWillaman** [comment]
Okay so what is the error now?

**Comment by GeorgeWillaman** [comment]
Okay so what is the error now?

**Comment by sejpalkalpesh** [comment]
![capture3](https://user-images.githubusercontent.com/46150285/51057035-75011500-160a-11e9-826d-db348f7a8376.JPG)
![capture4](https://user-images.githubusercontent.com/46150285/51057036-75011500-160a-11e9-83e3-66d1fedcae8e.JPG)
same as before you can test it from www.plusios.com ( avilable only in US region)

**Comment by GeorgeWillaman** [comment]
Yep, I had that error before too. I went through the code, and found at you need to add a few things to your .env file.
REACT_APP_ALGOLIA_INDEX='INDEXNAME'
ALGOLIA_INDEX='INDEXNAME'
Try adding that to both, update indexname with the proper index name and let me know if it works.
--
@nparsons08 Are you looking for some extra help w/ the docs? The .env doesn't cover everything, and there's a lot of options not listed there but that are in the code.

**Comment by sejpalkalpesh** [comment]
thanks, @GeorgeWillaman. I'll make a suggested change and try to build the frontend again.

**Comment by sejpalkalpesh** [comment]
thank you very much @GeorgeWillaman and @nparsons08 after stating up 
REACT_APP_ALGOLIA_INDEX='INDEXNAME'
ALGOLIA_INDEX='INDEXNAME'
in '.env' file, My problem is solved.

**Comment by sejpalkalpesh** [comment]
thank you very much @GeorgeWillaman and @nparsons08  for your kind support. After adding above mentioned env variables to .env file my issue is solved.

**Comment by sejpalkalpesh** [comment]
thank you very much  @GeorgeWillaman and @nparsons08 for your kind support after making changes to .env file my issue is solved.

**Comment by GeorgeWillaman** [comment]
> thank you very much @GeorgeWillaman and @nparsons08 for your kind support after making changes to .env file my issue is solved.

Glad I could help!
