### ISSUE TITLE
Redirect from http to https

### ISSUE THREAD

**Issue by mlapierre** [GetStream/Winds#57]
I get CORS errors when I try to log in unless I use https:

```
Fetch API cannot load https://winds.getstream.io/api/topics?limit=10&sort=createdAt%20DESC. 

Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains the invalid value ''. 
Origin 'http://winds.getstream.io' is therefore not allowed access. 
Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Logging in via https is fine, and preferable, so perhaps requests via http should be automatically redirected to https?

**Comment by nparsons08** [comment]
@mlapierre This is fixed in a later release. Can you please clear your cache? Alternatively, if you're running your own hosted version, modify the `.env` file to point to `https://winds.getstream.io`.

**Comment by mlapierre** [comment]
I tried it with caching disabled (via dev tools).

It looks like requests to the domain root are redirected, but requests to various routes aren't. I had http://winds.getstream.io/app/personalization-feed bookmarked, which doesn't redirect to https

**Comment by nparsons08** [comment]
I see the issue now. We're doing a client side redirect. A server side
redirect will come soon (next 24-48 hours) to allow for a permanent
redirect. We want all users on HTTPS for security reasons. Can you update
your bookmark for the time being? Sorry about that.

**Comment by mlapierre** [comment]
No problem, already done, just wanted to let you know :)

**Comment by nparsons08** [comment]
Thanks for the heads up. Very much appreciated! 👍
