### ISSUE TITLE
No articles showing for feed

### ISSUE THREAD

**Issue by mhingston** [GetStream/Winds#571]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

No articles showing for feed once it has been added (I've tried waiting as well as adding/removing it multiple times).

### Steps to Reproduce

1. New > New RSS
2. URL: https://anchor.fm/s/21bc734/podcast/rss
3. Add RSS
4. Click checkbox
5. Click Submit

**Expected behavior:** After waiting a few minutes I expect the items in the feed to show.

**Actual behavior:** We haven't found any articles for this RSS feed yet :(

**Reproduces how often:** 100%

### Versions

https://winds.getstream.io

### Additional Information

N/A

**Comment by mahboubii** [comment]
hey @mhingston, you were adding the wrong link to a rss feed. you had to add the main url as a podcast. (https://anchor.fm/emerge/)
This podcast is already in Winds:
https://winds.getstream.io/podcasts/5c5f1040b200a91cee6922c7
