### ISSUE TITLE
 A mercury API will stop soon

### ISSUE THREAD

**Issue by sejpalkalpesh** [GetStream/Winds#574]
Today, I just got an email from Mercury that [they have gone open source](https://github.com/postlight/mercury-parser) and [will stop their API soon](https://mailchi.mp/postlight/action-required-mercury-parser-api-will-sunset-in-60-days). so in future version mercury should be part of winds API or we should host it separately.

**Comment by mahboubii** [comment]
@sejpalkalpesh Thanks for letting us know. We will integrate it directly into Winds.

**Comment by mahboubii** [comment]
fixed in https://github.com/GetStream/Winds/commit/d9b4df53d3032d6c7dc9d9c1e9095ba11df549fa
