### ISSUE TITLE
Add feed via URL

### ISSUE THREAD

**Issue by dylan-k** [GetStream/Winds#575]
Some bookmarklets and browser extensions like Google's "RSS Subscription Extension" make it very easy to add a feed to any reader that provides a URL for adding feeds. inoreader and feedly for example both have this feature. Would it be possible for Winds to do this as well?

**Comment by mahboubii** [comment]
@dylan-k This is an interesting feature. We will definitely consider adding this to Winds. We value open-source contributions if you'd like to introduce this feature. I'd be happy to review and accept your PR.
