### ISSUE TITLE
Loss of control and logout issue

### ISSUE THREAD

**Issue by Edeard95** [GetStream/Winds#577]
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Closing window whilst episode playing, podcast continues to play. When relaunching player, podcast continues to play, but I am logged out and can't stop the podcast from playing and autoplaying all other episodes. 

### Steps to Reproduce

1. [First Step] Play a podcast
2. [Second Step] Close window
3. [and so on...] relaunch player

**Expected behavior:** [What you expect to happen] I would expect to be back into winds with control over what plays

**Actual behavior:** [What actually happens] I am logged out and can't control what is playing through speakers

**Reproduces how often:** [What percentage of the time does it reproduce?] every time in my experience

### Versions

You can get this information from the manu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by mahboubii** [comment]
@Edeard95 What version are you using and in which OS?

**Comment by Edeard95** [comment]
Hi,

Version 3.1.10

On Ubuntu 18.04

**Comment by 0msLaw** [comment]
I am facing the same issue.

**Steps to Reproduce**
[x] Play a podcast
[x] Close window
[x] relaunch player
Expected behavior: [>>] I would expect to be back into winds with control over what plays

Actual behavior: [>>] I am logged out and can't control what is playing through speakers

Reproduces how often: [All the time] every time in my experience

I'm on Ubuntu 18.10
Winds v 3.1.10 via snap

**Comment by 0msLaw** [comment]
Update: v 3.1.11 has fixed my issue. What about yours? @Edeard95

**Comment by charwhee** [comment]
I am having this same problem under Windows 10 using v 3.1.11
