### ISSUE TITLE
G Suite Status Dashboard

### ISSUE THREAD

**Issue by roberthchan** [GetStream/Winds#589]
### Description

Please enable javascript to see the table containing service performance information.

### Steps to Reproduce

1. Adding Feed RSS: https://www.google.com/appsstatus/rss/es
2. Clic to RSS added, see the new post
3. When i clic to see the full post, sendme a message

**Expected Whatch the post correctly:** 

**Actual behavior: message descriptión**

**Reproduces how often to all the articles:** 

### Versions
3.1.11

**Comment by mahboubii** [comment]
Unfortunately we don't support javascript while extracting the articles
