### ISSUE TITLE
Cannot add feed that includes ccTLD (Country Based URL)

### ISSUE THREAD

**Issue by sifex** [GetStream/Winds#59]
Cannot add a URL that includes a Country Coded TLD. 

**Example:**
ucunion.com works fine, but ucunion.com.au doesn't.

Looks like this is due to inbuilt pattern in the regex. See Screenshot Below
<img src="https://cloud.githubusercontent.com/assets/2058557/20585782/e4ef6714-b251-11e6-821a-61e545acab70.png" />

**Page:**
https://winds.getstream.io/app/personalization-feed

**Browser:**
Chrome/macOS 10.12

**Example URL:**
http://ucunion.com.au/feed/

Edit: 
This seems to be a DOM only issue, as when I remove it using dev tools it works fine.

**Comment by nparsons08** [comment]
Hey @sifex, good find. Do you mind making a PR with a quick fix to the regex pattern? I'll happily accept. Thanks!

**Comment by nparsons08** [comment]
Good PR! Thank you! 👍
