### ISSUE TITLE
Can't Add RSS feeds for CBC.ca 

### ISSUE THREAD

**Issue by ColtonYYZ** [GetStream/Winds#593]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

I have tried so many variations of the links below but can't seem to get anything to work. 

https://rss.cbc.ca/lineup/topstories.xml
https://rss.cbc.ca/lineup/world.xml
https://rss.cbc.ca/lineup/canada.xml
https://rss.cbc.ca/lineup/politics.xml
https://rss.cbc.ca/lineup/business.xml
https://rss.cbc.ca/lineup/health.xml
https://rss.cbc.ca/lineup/arts.xml
https://rss.cbc.ca/lineup/technology.xml
https://rss.cbc.ca/lineup/canada-toronto.xml

### Steps to Reproduce

Simply try and add a link from above and it will say "Oops, something went wrong. Please try again later."

**Expected behavior:** Be allowed to add it successfully

**Actual behavior:** Errors out.

**Reproduces how often:** 100%

### Version:  Newest downloaded today. When I click File > About Winds nothing happens.

You can get this information from the menu. Winds > About Winds.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by jackharrhy** [comment]
Old issue, but looking into this, the CBC.ca RSS feeds [have some erros if you run them through the W3C Feed validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Frss.cbc.ca%2Flineup%2Fcanada-newfoundland.xml).
