### ISSUE TITLE
Discussion: Shrinkwrapping dependencies

### ISSUE THREAD

**Issue by artivilla** [GetStream/Winds#60]
Not sure how prevalent this is in OS, but I just had a linter error and realized I had to stick to a previous version for my `eslint-plugin-jsx-a11y` devDependency. Have you considered shrinkwrapping dependencies?

**Comment by nparsons08** [comment]
Hey @artivilla, as you are aware, we are actively working on the Winds RSS platform. That being said, we're going to keep upgrading NPM dependencies as they become available. 

I understand that this is a pain, so I would suggest that you pull often and always run `npm update` when available. It's also a good idea to always be on the bleeding edge of Node.js as this is what we intend to run on. 

Once we are able to release a stable version, we'll start shrinkwrapping dependencies. Until then, please use the above recommendations. Also, a good tool for keeping up to date on dependencies is https://github.com/tjunnone/npm-check-updates.
