### ISSUE TITLE
Download link fails for version 3.2

### ISSUE THREAD

**Issue by rafaelcapucho** [GetStream/Winds#609]
In the page[1], in the main centered button (written 1), it gives a link for Windows that is [2], but it fails as "Access Denied", this link is for the version 3.2

it the link number 2, it returns the link to the version 3.1.16, which seems to be older [3].

![image](https://user-images.githubusercontent.com/163367/71609972-a3edff00-2b6b-11ea-9083-5b0846c6354d.png)

Also, it is being packaged without a Publisher, which triggered my Windows Defender:

![image](https://user-images.githubusercontent.com/163367/71609997-fcbd9780-2b6b-11ea-95ac-7d71ffc94082.png)

[1] - https://s3.amazonaws.com/winds-2.0-releases/latest.html
[2] - https://s3.amazonaws.com/winds-2.0-releases/releases/Winds%20Setup%203.2.0.exe
[3] - https://s3.amazonaws.com/winds-2.0-releases/releases/Winds%20Setup%203.1.16.exe

**Comment by mahboubii** [comment]
@rafaelcapucho link should be fixed.
