### ISSUE TITLE
Download page shows different versions to different systems

### ISSUE THREAD

**Issue by AdrianoCahete** [GetStream/Winds#615]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description
Assuming that the [Download page](https://s3.amazonaws.com/winds-2.0-releases/latest.html) is correct (the link is to Winds 2.0, but the code is on 3.0 already), it shows different versions to different systems:
| OS | Winds version |
| --- | -------------- |
| macOS (.dmg) | 3.2.0 |
| Windows (.exe) | 3.1.16 |
| Linux Distros (.AppImage) | 3.2.0 |

At this time, Github release artifacts are in 3.2.1, different from any of versions in Download page.

### Steps to Reproduce

1. Go the Download Page
2. See the link of versions and their versions

**Expected behavior:** All releases in the same version

**Actual behavior:** Github artifact is the latest version, Mac and Linux is one patch before and Windows is almost one minor version before.

**Reproduces how often:** Always

### Additional Information

Is this correct? If not, how I can get the latest Windows version?

**Comment by mahboubii** [comment]
Unfortunately the Windows build fails in recent macOS versions. We will release the updated version as soon as this issue is fixed.
