### ISSUE TITLE
Any plans for a dark mode or theme switch option

### ISSUE THREAD

**Issue by tammix** [GetStream/Winds#616]
Any possibility of adding a theme changing feature with dark mode in the options. That would help especially with reducing glare, it's also appealling design wise.
Thanks

**Comment by Dorson** [comment]
I coded a flexible and working solution for the Dark Mode.

Try demo in here:
https://dorson.github.io/CSS-Dark-Mode-and-color-switch/

Works with basic CSS variables + short JavaScript.

Can be used to define multiple color themes in the already existing CSS file.

**Have fun using my code !**
