### ISSUE TITLE
Make Winds installable: PWA

### ISSUE THREAD

**Issue by lomby92** [GetStream/Winds#623]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

This is not an issue, this is a feature request. It would be fantastic to be able to install the web app as a Progressive Web App. The manifest file and a simple serviceWorker.js would be enough to enable Chrome install's suggestion.

I will be happy to propose my solution as soon as possible

**Comment by mahboubii** [comment]
@lomby92 It's a great feature IMO, feel free to create a PR for it, We always welcome community contributions.

**Comment by lomby92** [comment]
After some days I had time to invest and this is the result in my Ubuntu menu:

![local app into menu](https://user-images.githubusercontent.com/5825081/81383410-46b51c00-9110-11ea-887b-41abe68829d9.png)

---

And this is how the app looks like:

![Schermata del 2020-05-08 09-39-49](https://user-images.githubusercontent.com/5825081/81383458-5e8ca000-9110-11ea-9b4d-951eab2dd9a2.png)

---

Now there is a problem, this project has the default set of `create-react-app` scripts.
This means that a service worker is already provided by default and there is no way to easily remove it.

What I have done is likely and hack because I remove the generated service worker (generated by a Webpack plugin) and I replace it with my JS file directly into the build folder.

So, to test it I had to generate a build and serve these files with `serve` package (added only as dev dependency)

---

@mahboubii  What do you think about this approach?

**Comment by lomby92** [comment]
Mark as resolved. See #637
