### ISSUE TITLE
Idea: Curated/Personalized Weekly Email

### ISSUE THREAD

**Issue by nparsons08** [GetStream/Winds#63]
Send out an optional curated/personalized email on a weekly basis featuring popular blog posts.

**Comment by mlapierre** [comment]
Would the email be composed of popular blog posts on sites the user _doesn't_ subscribe to? That could be a useful alternative to suggested feeds, although I think I'd prefer an in-app list of suggested feeds showing a selection of curated/personalized posts from each feed.

**Comment by nparsons08** [comment]
@mlapierre We're not sure just yet. It's something that we are still planning out. What would you prefer? We are rolling out an in-app suggested feeds component early the coming days. I'll ping you here when we release the feature.

**Comment by mlapierre** [comment]
Well, I know some people prefer email to RSS so it might be useful for them, but I would prefer something within the app.

**Comment by nparsons08** [comment]
Cool. Stay tuned!
