### ISSUE TITLE
Links for desktop installer broken.

### ISSUE THREAD

**Issue by medic-code** [GetStream/Winds#646]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filed: https://github.com/GetStream/Winds/issues

### Description

Opening https://s3.amazonaws.com/winds-2.0-releases/latest.html, none of the links for Windows, Mac or Linux are working. Error message follows. See below.

### Steps to Reproduce

1. Open https://s3.amazonaws.com/winds-2.0-releases/latest.html
2. Click the links 

**Expected behavior:** [What you expect to happen]

Expect to download the installer 
**Actual behavior:** [What actually happens]
On clicking on installers

Error Message:
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>AHDR1K4X8P2MBJBY</RequestId>
<HostId>OU8w4EP74taHSgpL7SXbv0qN3L4ezdtPqcKPw4ESuBLfkD0D9gF1fFAclzTDNCnJWoWP8OpiyH8=</HostId>
</Error>

**Reproduces how often:** [What percentage of the time does it reproduce?]

100% of time

**Comment by ngetchell** [comment]
The newest one I could find was 3.0.0. Here is a working download link.

https://s3.amazonaws.com/winds-2.0-releases/releases/Winds%20Setup%203.0.0.exe

**Comment by balthasars** [comment]
Same thing happens for the Mac link, install using Homebrew works however:
```
brew cask install winds
```

**Comment by evdcush** [comment]
Why aren't the AppImages simply hosted in [releases](https://github.com/GetStream/Winds/releases)?

**Comment by serpro69** [comment]
I tried to find a download link and it doesn't seem to work: the link in the readme navigates to the website, and there clicking on download gets you back to this repo.
Is there a link where official AppImages can be downloaded?
