### ISSUE TITLE
Cannot SignUp

### ISSUE THREAD

**Issue by shprink** [GetStream/Winds#7]
![image](https://cloud.githubusercontent.com/assets/1388706/20211148/77509236-a7fd-11e6-8be4-f1d2ea2eeaf8.png)

Response:

![image](https://cloud.githubusercontent.com/assets/1388706/20211152/810bdb14-a7fd-11e6-9691-3d9f1f34e813.png)

**Comment by nparsons08** [comment]
Hey @shprink, can you clear your local storage and cache? Then give it another shot? If the issue persists, we'll have a look. Thanks!

**Comment by shprink** [comment]
Same problem. Here is the payload I send

![image](https://cloud.githubusercontent.com/assets/1388706/20221594/3e64077a-a832-11e6-9fe3-414948dd6330.png)

**Comment by nparsons08** [comment]
Thanks @shprink. Can you ping me at nick@getstream.io? I'd like to get this issue resolved for you as soon as possible. Additionally, can you provide me with your OS, Browser, etc.?

**Comment by shprink** [comment]
OSX & Chrome but that's clearly a server issue. The payload the Http request uses seems ok to me.

**Comment by nparsons08** [comment]
Absolutely agree.
