### ISSUE TITLE
Can't merge recent changes on Windows

### ISSUE THREAD

**Issue by mlapierre** [GetStream/Winds#73]
I'm no longer to merge the changes as of commit e52514c4e08f1247f533c61e1f66393f2b67499b

One of the assets in the .tmp directory includes a colon in the path, which windows doesn't like:

```
λ git pull upstream master
From https://github.com/GetStream/Winds
 * branch            master     -> FETCH_HEAD
Updating 666c17a..7ad717a
fatal: cannot create directory at '.tmp/public/js/app/https:': Invalid argument
```

**Comment by nparsons08** [comment]
Can you try running `git stash` and then `git pull`? That http directory/file was something that accidentally got merged into version control. Sorry about that.

**Comment by mlapierre** [comment]
The actual file is still in master: .tmp/public/js/app/https:/dzgr2e2po1y82.cloudfront.net/styles/app/styles.css

**Comment by mlapierre** [comment]
Incidentally, this is what would greet anyone starting out on Windows:

```
λ git clone https://github.com/GetStream/Winds.git
Cloning into 'Winds'...
remote: Counting objects: 3777, done.
remote: Compressing objects: 100% (269/269), done.
remote: Total 3777 (delta 124), reused 0 (delta 0), pack-reused 3457R
Receiving objects: 100% (3777/3777), 44.38 MiB | 90.00 KiB/s, done.
Resolving deltas: 100% (1820/1820), done.
fatal: cannot create directory at '.tmp/public/js/app/https:': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by mlapierre** [comment]
I got around it by cloning on linux, removing the .tmp directory, then pulling from that clone into windows.
