### ISSUE TITLE
Idea: Docker support

### ISSUE THREAD

**Issue by julianxhokaxhiu** [GetStream/Winds#8]
What about an official Docker for this awesome project?

Thank you in advance :)

**Comment by nparsons08** [comment]
Great idea @julianxhokaxhiu! Would you be up for writing a Docker compose file?

**Comment by nparsons08** [comment]
Absolutely @julianxhokaxhiu. I'll get started on that today. Can you ping me at nick@getstream.io so we can collaborate via email?

**Comment by julianxhokaxhiu** [comment]
Sure!

**Comment by julianxhokaxhiu** [comment]
I'll provide a PR tomorrow :)
