### ISSUE TITLE
Automated install?

### ISSUE THREAD

**Issue by danielbayley** [GetStream/Winds#83]
For instance on macOS, ideally you would be able to install with [_homebrew-cask_](https://caskroom.github.io)…

**Comment by nparsons08** [comment]
@danielbayley Great idea. https://github.com/caskroom/homebrew-cask/pull/27694

**Comment by danielbayley** [comment]
@nparsons08 Ah that's a simple cask actually… I should have just done it myself only I had briefly looked at the _Installation_ section of the README and figured it might be a bit more involved…

Nice one! 👍

**Comment by nparsons08** [comment]
@danielbayley Thanks! You can now run `brew cask install winds` to get the latest version of the native app!
