### ISSUE TITLE
Feed add showing clear or white text. Can't see entry

### ISSUE THREAD

**Issue by clickbrain** [GetStream/Winds#87]
Using Safari 10.0.1 on MacOS. 

Click + sign in top right to add a feed. Get form to enter I assume a URL to a feed. When I type the feed, I can't see what I am typing, but cursor moves to right. 

If I hit enter, nothing happens that is visible. 

![winds____powered_by_getstream_io](https://cloud.githubusercontent.com/assets/963889/21121188/03ab5974-c099-11e6-929b-1a45a99f7875.png)

**Comment by clickbrain** [comment]
Update: Just finished posting this and went back to Winds and the feed I typed in is loaded.

**Comment by nparsons08** [comment]
Hey @clickbrain, there's a known issue with placeholder colors not displaying properly in Safari. We'll get a fix shipped out as soon as possible. In the meantime, do you mind using Chrome for a better experience? Thanks!

**Comment by clickbrain** [comment]
Hey Nick. This is Brad Nickel. We exchanged emails today about Safari.

**Comment by nparsons08** [comment]
Hey @clickbrain, out of curiosity, do any errors show up in your console after hitting enter? It sometimes takes a few seconds for our parser to follow redirects, etc. before parsing the RSS feed.

**Comment by nparsons08** [comment]
@dwightgunning are you able to tackle this one? It should be nearly identical to the other task. If not, just let me know! :) 💯

**Comment by dwightgunning** [comment]
PR #94 raised.
