### ISSUE TITLE
Bug: RSS is outdated

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#89]
![image](https://cloud.githubusercontent.com/assets/265409/21653648/71ef7066-d2b2-11e6-89a0-f9e8ab122c59.png)

**Comment by nparsons08** [comment]
@tschellenbach I think our worker processes are having a hard time keeping up with the content. They do update the content, but not fast enough... so data appears to lag by about 5 hours to a day. It's intermittent.
