### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by tschellenbach** [GetStream/Winds#90]

**Comment by dwightgunning** [comment]
__finds the tweakers rss feed__

The Tweakers webpage is interesting. It returns a HTTP 202 and a very slim HTML document containing a cookie consent form over the top of a fullscreen image that's a blurred version of their regular website. There's no real way to discover a feed without trying various alternative URLs based on the domain (e.g. /rss.xml /atom.xml).

_proposal_: If we want to come back to this later, I'd mark the test skipped. Alternatively if it's not a use-case that we think we can support, let's just remove  the test.

**Comment by dwightgunning** [comment]
@nparsons08 do you have thoughts on this?

**Comment by nparsons08** [comment]
This issue will be resolved in the next release. Closing out for now.
