### ISSUE TITLE
RSS feed not detected from Quora.com links

### ISSUE THREAD

**Issue by iandouglas** [GetStream/Winds#91]
Finding a topic on Quora, and adding "/rss" to the end of the URL presents you with an RSS feed of new posts within that topic, for example:

https://www.quora.com/topic/Python-programming-language-1/rss

Winds is currently unable to parse the RSS feed and reports a "Feed Missing" in the UI. The console reports a 502 error on the URL: https://winds.getstream.io/api/rss/discover?url=www.quora.com%2Ftopic%2FNewsfeed%2Frss

**Comment by iandouglas** [comment]
Does the RSS parser handle https links properly, or follow redirects if a server redirects to a secure URL if you attempt to fetch a non-secure version of the URL? I notice in the `url=` parameter that it has dropped the 'https://' portion of the URL I pasted into Winds.

**Comment by nparsons08** [comment]
This issue will be addressed in the next release of Winds (with the updated OPML parser). Closing out the issue for now.
