### ISSUE TITLE
Add Feed: Long URLs overlap the submit button

### ISSUE THREAD

**Issue by dwightgunning** [GetStream/Winds#95]
The input field for adding feeds allows the URL to overlap the button, see below.

<img width="1223" alt="screen shot 2017-01-18 at 9 03 59 pm" src="https://cloud.githubusercontent.com/assets/454042/22080898/afd2e3d0-ddc1-11e6-9c40-e12a8abc0c46.png">

**Comment by artivilla** [comment]
How would you like to fix this? Reduce font size or adjust the font size based on characters?

**Comment by nparsons08** [comment]
Since there hasn't been any activity around this topic, we're going to close the issue. Please submit a PR if you're interested in adding this fix. Thank you!
