### ISSUE TITLE
Polish UTF-8 characters displayed incorrectly

### ISSUE THREAD

**Issue by Newarr** [GetStream/Winds#96]
I noticed that for some RSS feeds Polish UTF-8 characters are displayed incorrectly. I thought that it may be an issue with the RSS source itself, but in e.g. Inoreader they display correctly. 

The link of the feed displayed below:   ##http://www.rp.pl/rss/1037

![winds -- powered by getstream io](https://cloud.githubusercontent.com/assets/22638839/22857801/f1a8477a-f0ac-11e6-9334-7663161b0c4f.jpg)

**Comment by nparsons08** [comment]
Since there hasn't been any activity around this topic, we're going to close the issue. Please submit a PR if you're interested in adding this functionality. Thank you!
