### ISSUE TITLE
Min .env setup to get Winds running locally

### ISSUE THREAD

**Issue by artivilla** [GetStream/Winds#97]
So it's been a while but I updated my repo and tried getting my local setup working, it's giving me the following when attempting to run load_initial_data.js (using node v7):
```
/Users/artichandok/Dropbox/Remote/Winds/node_modules/sails/node_modules/include-all/lib/help-include-all-sync.js:281
              throw e;
              ^

`include-all` attempted to `require(/Users/artichandok/Dropbox/Remote/Winds/config/passport.js)`, but an error occurred::
Details:TypeError: JwtStrategy requires a secret or key
```
So far I've setup my stream keys and API_BASE_URL only. Running node v7.

**Comment by dwightgunning** [comment]
A secret value is needed for Passport's JWT authentication. It's unrelated to your winds keys and tokens. Just set the JWT_SECRET config variable in the `.env` file and you'll be good to go.

**Comment by artivilla** [comment]
Details:TypeError: OAuth2Strategy requires a clientID option. Am I missing another config value?

**Comment by artivilla** [comment]
Nvm. Got it! Was missing fb auth keys as well.

**Comment by dwightgunning** [comment]
Glad you got it!

We ought to explain these in the readme; I'll create an issue.
