### ISSUE TITLE
Extract SVGs

### ISSUE THREAD

**Issue by artivilla** [GetStream/Winds#98]
Since this isn't a pressing issue but wanted to start with something a little simpler. Would be happy to extract svgs into their own setup. There are a few plugins, atomic-app/react-svg and boopathi/react-svg-loader come to mind. Thoughts on this?

**Comment by dwightgunning** [comment]
Interesting; I've not seen these projects as I'm relatively new to react. What are the main benefits; improving the modularity and readability of the codebase?

**Comment by artivilla** [comment]
Pretty much for starters, also the svgs can get cached if served from a siloed dir. But mostly readability and reuse.
